import {ROUTES,SORTS,STATES,filterOpportunities,paginate,availableIndustries,filterNews,selectOpportunity,dashboardStatus,routeHref} from "./dashboard-core.js";

export const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const finite=value=>typeof value==="number"&&Number.isFinite(value);
const fmt=(value,digits=2)=>finite(value)?value.toLocaleString(undefined,{minimumFractionDigits:digits,maximumFractionDigits:digits}):"—";
const pct=(value,digits=2)=>finite(value)?`${value>0?"+":""}${fmt(value,digits)}%`:"—";
const compact=value=>finite(value)?Intl.NumberFormat(undefined,{notation:"compact",maximumFractionDigits:1}).format(value):"—";
const clock=value=>{const time=Date.parse(value||"");return Number.isFinite(time)?new Date(time).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}):"—";};
const dateTime=value=>{const time=Date.parse(value||"");return Number.isFinite(time)?new Date(time).toLocaleString([],{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}):"—";};
const tone=value=>finite(value)?value>0?"positive":value<0?"negative":"neutral":"muted";
const stateTone=value=>({CONFIRMED:"positive",CONFIRMING:"cyan",EMERGING:"blue",DEGRADING:"amber",REVERSED:"violet",NO_TREND:"muted"}[value]||"muted");
const safeUrl=value=>{try{const url=new URL(value);return url.protocol==="https:"?url.href:null;}catch{return null;}};
const checked=(array,value)=>array.includes(value)?" checked":"";
const selected=(actual,value)=>actual===value?" selected":"";

function badge(text,kind="muted"){return `<span class="badge ${esc(kind)}">${esc(text||"—")}</span>`;}
function freshness(value){return badge(value?.state||"UNAVAILABLE",String(value?.state||"unavailable").toLowerCase());}
function direction(row){if(!row?.v1_direction)return `<span class="direction-none" title="Last evidence bias: ${esc(row?.last_evidence_bias||"none")}">—</span>`;return badge(row.v1_direction,row.v1_direction==="LONG"?"positive":"negative");}
function stateBadge(row){const label=row.v1_state==="REVERSED"?`REVERSED → ${row.v1_direction||"—"}`:row.v1_state;return badge(label,stateTone(row.v1_state));}
function tmCell(row){const values=["5","15","30","60"].map(key=>row.trend_magic?.timeframes?.[key]);const known=values.filter(value=>value?.state);if(!known.length)return `<span class="muted">Warming up</span>`;return `<div class="tm-dots" title="${esc(row.trend_magic?.agreement_pattern||"")}">${values.map((value,index)=>`<span class="tm-dot ${value?.state==="BLUE"?"up":value?.state==="RED"?"down":"warm"}">${[5,15,30,60][index]}</span>`).join("")}</div>`;}
function newsLink(item,small=false){const url=safeUrl(item?.url);const title=esc(item?.headline||"No current headline");return `<div class="news-line${small?" compact":""}"><span class="news-time">${clock(item?.first_seen_at)}</span><span>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${title}</a>`:title}<small>${esc(item?.source||"Unknown source")} · ${esc(item?.category||"UNCLASSIFIED")}</small></span></div>`;}
function relatedNews(row,model){const news=model?.news||[];const groups={company:row.news||[],industry:news.filter(item=>row.industry&&(item.industry||[]).includes(row.industry)&&!(item.symbols||[]).includes(row.symbol)),sector:news.filter(item=>row.sector&&(item.sector||[]).includes(row.sector)&&!(item.symbols||[]).includes(row.symbol)),market:news.filter(item=>item.scope==="MARKET")};const labels={company:"Company news",industry:"Industry news",sector:"Sector news",market:"Market news"};return Object.entries(labels).map(([key,label])=>{const items=groups[key]||[];return `<div class="related-news"><strong>${label}</strong>${items.slice(0,3).map(item=>newsLink(item,true)).join("")||`<small>None currently mapped.</small>`}</div>`;}).join("");}
function why(row){return (row.why_picked||[]).length?row.why_picked.map(value=>`<span>${esc(value)}</span>`).join(""):"<span>Discovery evidence unavailable</span>";}

function opportunityRows(rows,{compactHome=false,watchlist=new Set()}={}){
  if(!rows.length)return `<tr><td colspan="13" class="empty">No opportunities match the current filters.</td></tr>`;
  return rows.map(row=>`<tr data-symbol="${esc(row.symbol)}" class="selectable-row${row.freshness?.quote?.state==="STALE"?" stale-row":""}">
    <td><button class="symbol-button" data-action="select" data-symbol="${esc(row.symbol)}">${esc(row.symbol)}</button><small>${esc(row.company_name||"")}</small></td>
    <td>${direction(row)}</td><td>${stateBadge(row)}</td><td>${tmCell(row)}</td>
    <td><div class="why-cell">${why(row)}</div></td><td class="${tone(row.change_1d_pct)}">${pct(row.change_1d_pct)}</td><td class="${tone(row.move_5m_pct)}">${pct(row.move_5m_pct)}</td>
    <td><strong>${compact(row.session_volume)}</strong><small>RVOL ${fmt(row.finviz_rvol,2)}</small></td><td>${fmt(row.efficiency,2)}</td><td class="${tone(row.market_relative)}">${pct(row.market_relative)}</td>
    <td><span>${esc(row.sector||"Unknown")}</span><small>${esc(row.industry||"Unknown")}</small></td>
    <td>${row.news?.length?`<span class="catalyst-dot"></span>${esc(row.news[0].category)}`:`<span class="muted">No news</span>`}</td>
    <td><button class="icon-button" data-action="watch" data-symbol="${esc(row.symbol)}" aria-label="${watchlist.has(row.symbol)?"Remove from":"Add to"} watchlist">${watchlist.has(row.symbol)?"★":"☆"}</button><button class="view-button" data-action="select" data-symbol="${esc(row.symbol)}">View</button></td>
  </tr>`).join("");
}

function radarTable(rows,options={}){return `<div class="radar-table-wrap"><table class="radar-table${options.compactHome?" home-table":""}"><colgroup><col class="c-symbol"><col class="c-direction"><col class="c-state"><col class="c-tm"><col class="c-why"><col class="c-number"><col class="c-number"><col class="c-volume"><col class="c-eff"><col class="c-rel"><col class="c-sector"><col class="c-news"><col class="c-action"></colgroup><thead><tr><th>Symbol</th><th>Direction</th><th>Trend State</th><th>Trend Magic</th><th>Why it was picked</th><th>1D</th><th>5m</th><th>Volume / RVOL</th><th>Efficiency</th><th>Rel. Strength</th><th>Sector / Industry</th><th>Catalyst / News</th><th>Action</th></tr></thead><tbody>${opportunityRows(rows,options)}</tbody></table></div>`;}

function marketChange(item){return finite(item.change_pct)?item.change_pct:item.change_1d_pct;}
function macroStatus(item){if(item.freshness?.state==="STALE")return freshness(item.freshness);if(item.delayed===true)return badge("DELAYED","delayed");return freshness(item.freshness);}
function marketPanel(model){return `<article class="panel summary-card"><div class="panel-title"><div><span class="eyebrow">BROAD MARKET</span><h2>Market pulse</h2></div><a href="${routeHref("market",model.data_mode.startsWith("SIMULATED"))}">View all →</a></div><div class="market-list">${(model.market||[]).slice(0,8).map(item=>`<div><span><strong>${esc(item.key||item.symbol)}</strong><small>${esc(item.label||item.key||item.symbol)}</small></span><span class="metric-value">${fmt(item.value,2)}<small class="${tone(marketChange(item))}">${pct(marketChange(item))}</small>${macroStatus(item)}</span></div>`).join("")}</div></article>`;}
function marketNewsPanel(model){return `<article class="panel summary-card"><div class="panel-title"><div><span class="eyebrow">MARKET NEWS</span><h2>News &amp; catalysts</h2></div><a href="${routeHref("news",model.data_mode.startsWith("SIMULATED"))}">Live feed →</a></div><div class="news-list">${(model.market_news||[]).slice(0,4).map(item=>newsLink(item,true)).join("")||`<p class="empty">No current broad-market headline.</p>`}</div></article>`;}
function groupPanel(title,eyebrow,rows,route,model){return `<article class="panel summary-card"><div class="panel-title"><div><span class="eyebrow">${esc(eyebrow)}</span><h2>${esc(title)}</h2></div><a href="${routeHref(route,model.data_mode.startsWith("SIMULATED"))}">Explore →</a></div><div class="group-bars">${rows.slice(0,6).map(row=>`<div><span>${esc(row.name)}<small>${row.radar_member_count} radar</small></span><span class="bar-track"><i class="${tone(row.performance_1d_pct)}" style="width:${Math.min(100,Math.max(5,Math.abs(row.performance_1d_pct||0)*15))}%"></i></span><strong class="${tone(row.performance_1d_pct)}">${pct(row.performance_1d_pct)}</strong></div>`).join("")||`<p class="empty">Unavailable</p>`}</div></article>`;}

function detail(row,{inline=false,model=null}={}){
  if(!row)return `<article class="panel detail-panel"><p class="empty">Select an opportunity to inspect its evidence.</p></article>`;
  const tms=[5,15,30,60].map(frame=>{const value=row.trend_magic?.timeframes?.[String(frame)];return `<div><span>${frame}m</span>${value?.state?badge(value.state,value.state==="BLUE"?"positive":"negative"):badge(value?.status||"UNAVAILABLE","muted")}</div>`;}).join("");
  return `<article class="${inline?"":"panel "}detail-panel"><div class="detail-head"><div><span class="eyebrow">SECURITY DETAIL</span><h2>${esc(row.symbol)}</h2><p>${esc(row.company_name||"")}</p></div>${inline?"":`<button class="close-button" data-action="close-detail" aria-label="Close details">×</button>`}</div>
    <div class="detail-badges">${direction(row)}${stateBadge(row)}${freshness(row.freshness?.quote)}</div>
    ${row.v1_state==="REVERSED"?`<p class="callout">Current ${esc(row.v1_direction)} · reversed from ${esc(row.reversed_from||"prior direction")}</p>`:""}
    <div class="detail-price"><strong>$${fmt(row.price)}</strong><span class="${tone(row.change_1d_pct)}">${pct(row.change_1d_pct)} today</span></div>
    <h3>Trend Magic <small>Descriptive only</small></h3><div class="tm-grid">${tms}</div>
    <h3>Relative strength</h3><dl><dt>vs ${esc(row.benchmark_symbol||"broad benchmark")}</dt><dd>${pct(row.market_relative)}</dd><dt>vs sector</dt><dd>${pct(row.sector_relative)}</dd><dt>vs industry</dt><dd>${pct(row.industry_relative)}</dd><dt>Peer breadth</dt><dd>${finite(row.peer_breadth)?pct(row.peer_breadth*100):"—"}</dd></dl>
    <h3>Key metrics</h3><dl><dt>Efficiency</dt><dd>${fmt(row.efficiency,2)}</dd><dt>Persistence</dt><dd>${fmt(row.persistence,2)}</dd><dt>5m move</dt><dd>${pct(row.move_5m_pct)}</dd><dt>Live volume</dt><dd>${compact(row.session_volume)}</dd><dt>Finviz RVOL</dt><dd>${fmt(row.finviz_rvol,2)}</dd><dt>Average volume</dt><dd>${compact(row.avg_volume)}</dd></dl>
    <h3>Why it was picked</h3><div class="tag-list">${why(row)}</div>
    <h3>Sector / industry</h3><p>${esc(row.sector||"Unknown")} · ${esc(row.industry||"Unknown")}</p>
    <h3>Catalyst &amp; news</h3><div class="news-list">${relatedNews(row,model)}</div>
    <details><summary>Evidence &amp; provenance</summary><dl><dt>Quote source</dt><dd>${esc(row.provenance?.price||"—")}</dd><dt>V1 state source</dt><dd>${esc(row.provenance?.v1_state||"—")}</dd><dt>Classification</dt><dd>${esc(row.provenance?.classification||"—")}</dd><dt>First nominated</dt><dd>${dateTime(row.first_nominated_at)}</dd><dt>Last nominated</dt><dd>${dateTime(row.last_nominated_at)}</dd><dt>Structural break</dt><dd>${row.structural_break?`${esc(row.structural_break.direction)} · ${clock(row.structural_break.at)}`:"—"}</dd></dl></details>
  </article>`;
}

function home(model,ui){const rows=(model.opportunities||[]).slice(0,9);const selected=selectOpportunity(model,ui.selectedSymbol)||rows[0];return `<div class="summary-grid">${marketPanel(model)}${marketNewsPanel(model)}${groupPanel("Sector performance","CURRENT RADAR",model.sectors||[],"sectors",model)}${groupPanel("Top industries","LEADERS & LAGGARDS",model.industries||[],"sectors",model)}</div><div class="home-main"><section class="panel radar-panel"><div class="panel-title"><div><span class="eyebrow">NEWEST &amp; MEANINGFULLY CHANGED</span><h2>Opportunity Radar</h2></div><a href="${routeHref("opportunities",ui.demo)}">Open full radar →</a></div>${radarTable(rows,{compactHome:true,watchlist:ui.watchlist})}</section>${detail(selected,{inline:true,model})}</div>`;}

function filterControls(model,ui){const f=ui.filters;const sectors=[...new Set((model.opportunities||[]).map(row=>row.sector).filter(Boolean))].sort();const industries=availableIndustries(model.opportunities,f.sector);const sensors=[...new Set((model.opportunities||[]).flatMap(row=>(row.finviz_sensors||[]).map(value=>value.sensor)).filter(Boolean))].sort();return `<form id="radarFilters" class="filter-panel panel"><div class="filter-main"><label>Search<input name="query" value="${esc(f.query)}" placeholder="Ticker or company"></label><label>Asset<select name="asset"><option value="ALL">Stocks &amp; ETFs</option><option value="STOCK"${selected(f.asset,"STOCK")}>Stocks</option><option value="ETF"${selected(f.asset,"ETF")}>ETFs</option></select></label><label>Sector<select name="sector"><option value="ALL">All sectors</option>${sectors.map(value=>`<option${selected(f.sector,value)}>${esc(value)}</option>`).join("")}</select></label><label>Industry<select name="industry"><option value="ALL">All industries</option>${industries.map(value=>`<option${selected(f.industry,value)}>${esc(value)}</option>`).join("")}</select></label><label>Catalyst<select name="catalyst"><option value="ALL">All news states</option><option value="FRESH"${selected(f.catalyst,"FRESH")}>Fresh catalyst</option><option value="ANY"${selected(f.catalyst,"ANY")}>Has news</option><option value="NONE"${selected(f.catalyst,"NONE")}>No news</option></select></label><label>Sensor<select name="sensor"><option value="ALL">All sensors</option>${sensors.map(value=>`<option${selected(f.sensor,value)} value="${esc(value)}">${esc(value.replaceAll("TREND_","").replaceAll("_"," "))}</option>`).join("")}</select></label><label>Sort<select name="sort">${Object.entries(SORTS).map(([value,label])=>`<option value="${value}"${selected(f.sort,value)}>${esc(label)}</option>`).join("")}</select></label></div><div class="filter-toggles"><fieldset><legend>Direction</legend><label><input type="checkbox" name="direction" value="LONG"${checked(f.directions,"LONG")}>Long</label><label><input type="checkbox" name="direction" value="SHORT"${checked(f.directions,"SHORT")}>Short</label></fieldset><fieldset><legend>State</legend>${STATES.map(value=>`<label><input type="checkbox" name="state" value="${value}"${checked(f.states,value)}>${esc(value.replaceAll("_"," "))}</label>`).join("")}</fieldset><label><input type="checkbox" name="watchlistOnly"${f.watchlistOnly?" checked":""}>Watchlist only</label><label><input type="checkbox" name="freshOnly"${f.freshOnly?" checked":""}>Fresh data only</label><button type="button" class="quiet-button" data-action="clear-filters">Clear all</button></div></form>`;}

function opportunities(model,ui){const filtered=filterOpportunities(model.opportunities,ui.filters,ui.watchlist);const pages=paginate(filtered,ui.filters.page,ui.filters.pageSize);return `${filterControls(model,ui)}<section class="panel"><div class="panel-title"><div><span class="eyebrow">USER-CONTROLLED ORDERING</span><h2>Opportunity Radar</h2></div><span>${pages.total} of ${model.opportunities.length} visible · rank ≠ entry signal</span></div>${radarTable(pages.rows,{watchlist:ui.watchlist})}<div class="pagination"><button data-action="page" data-page="${pages.page-1}"${pages.page<=1?" disabled":""}>← Previous</button><span>Page ${pages.page} / ${pages.pages}</span><button data-action="page" data-page="${pages.page+1}"${pages.page>=pages.pages?" disabled":""}>Next →</button></div></section>`;}

function market(model){const sections=[["BROAD INDEXES",["SPY","QQQ","IWM"]],["VOLATILITY",["VIX"]],["RATES",["US2Y","US10Y"]],["DOLLAR",["DXY"]],["COMMODITIES",["WTI"]]];return `<div class="market-sections">${sections.map(([title,symbols])=>`<section class="panel"><span class="eyebrow">${title}</span><div class="metric-cards">${symbols.map(symbol=>{const row=model.market.find(value=>(value.key||value.symbol)===symbol)||{};return `<article><div><strong>${esc(row.key||row.symbol||symbol)}</strong><small>${esc(row.label||symbol)}</small></div><b>${fmt(row.value)}</b><span class="${tone(marketChange(row))}">${pct(marketChange(row))}</span>${macroStatus(row)}<small>${esc(row.source||"UNAVAILABLE")}${row.source_symbol?` · ${esc(row.source_symbol)}`:""}</small></article>`;}).join("")}</div></section>`).join("")}</div><div class="two-column">${groupPanel("Leading sectors","DERIVED RADAR CONTEXT",model.sectors||[],"sectors",model)}${groupPanel("Leading industries","DERIVED RADAR CONTEXT",model.industries||[],"sectors",model)}</div>${marketNewsPanel(model)}`;}

function groupTable(rows,type){if(!rows.length)return `<p class="empty">No ${esc(type)} data available.</p>`;return `<table class="group-table"><thead><tr><th>${esc(type)}</th><th>1D</th><th>5m</th><th>Breadth</th><th>Radar</th><th>Leaders</th><th>Laggards</th></tr></thead><tbody>${rows.map(row=>`<tr><td><button data-action="group" data-group-type="${type.toLowerCase()}" data-group="${esc(row.name)}">${esc(row.name)}</button><small>${esc(row.source)}</small></td><td class="${tone(row.performance_1d_pct)}">${pct(row.performance_1d_pct)}</td><td class="${tone(row.performance_5m_pct)}">${pct(row.performance_5m_pct)}</td><td>${finite(row.breadth)?pct(row.breadth*100):"—"}</td><td>${row.radar_member_count}</td><td>${esc((row.leaders||[]).join(" · "))}</td><td>${esc((row.laggards||[]).join(" · "))}</td></tr>`).join("")}</tbody></table>`;}
function sectors(model,ui){const chosen=ui.groupSelection;const peers=chosen?(model.opportunities||[]).filter(row=>row.sector===chosen.name||row.industry===chosen.name):[];return `<div class="two-column sector-columns"><section class="panel"><div class="panel-title"><div><span class="eyebrow">CURRENT RADAR PEER UNIVERSE</span><h2>Sectors</h2></div><span>Descriptive only</span></div>${groupTable(model.sectors||[],"Sector")}</section><section class="panel"><div class="panel-title"><div><span class="eyebrow">FINVIZ CLASSIFICATION</span><h2>Industries</h2></div><span>Click to inspect</span></div>${groupTable(model.industries||[],"Industry")}</section></div>${chosen?`<section class="panel"><div class="panel-title"><div><span class="eyebrow">SELECTED ${esc(chosen.type.toUpperCase())}</span><h2>${esc(chosen.name)}</h2></div><button data-action="clear-group" class="quiet-button">Close</button></div>${radarTable(peers,{watchlist:ui.watchlist})}</section>`:""}`;}

function newsFilters(model,ui){const f=ui.newsFilters;const sectors=[...new Set((model.news||[]).flatMap(row=>row.sector||[]))].sort();const categories=[...new Set((model.news||[]).map(row=>row.category).filter(Boolean))].sort();return `<form id="newsFilters" class="filter-panel panel"><div class="filter-main"><label>Scope<select name="scope"><option value="ALL">All scopes</option>${["COMPANY","INDUSTRY","SECTOR","MARKET","MULTI_COMPANY"].map(value=>`<option${selected(f.scope,value)}>${value}</option>`).join("")}</select></label><label>Category<select name="category"><option value="ALL">All categories</option>${categories.map(value=>`<option${selected(f.category,value)}>${esc(value)}</option>`).join("")}</select></label><label>Symbol<input name="symbol" value="${esc(f.symbol)}" placeholder="AMD"></label><label>Sector<select name="sector"><option value="ALL">All sectors</option>${sectors.map(value=>`<option${selected(f.sector,value)}>${esc(value)}</option>`).join("")}</select></label><label>Time range<select name="range"><option value="ALL">All retained</option><option value="1"${selected(f.range,"1")}>Past hour</option><option value="4"${selected(f.range,"4")}>Past 4 hours</option><option value="24"${selected(f.range,"24")}>Past day</option></select></label><label>Sort<select name="sort"><option value="firstSeen"${selected(f.sort,"firstSeen")}>Newest first observed</option><option value="published"${selected(f.sort,"published")}>Newest published</option></select></label></div></form>`;}
function news(model,ui){const rows=filterNews(model.news,ui.newsFilters);return `${newsFilters(model,ui)}<section class="panel"><div class="panel-title"><div><span class="eyebrow">CAUSAL ORDER: FIRST OBSERVED</span><h2>News &amp; Catalysts</h2></div><span>${rows.length} headlines</span></div><table class="news-table"><thead><tr><th>First seen</th><th>Published</th><th>Headline</th><th>Source</th><th>Scope</th><th>Category</th><th>Symbols</th><th>Sector</th><th>Industry</th></tr></thead><tbody>${rows.map(item=>{const url=safeUrl(item.url);return `<tr><td>${dateTime(item.first_seen_at)}</td><td>${dateTime(item.publication_at)}</td><td>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(item.headline)}</a>`:esc(item.headline)}</td><td>${esc(item.source||"—")}</td><td>${badge(item.scope)}</td><td>${esc(item.category)}</td><td>${esc((item.symbols||[]).join(" · ")||"—")}</td><td>${esc((item.sector||[]).join(" · ")||"—")}</td><td>${esc((item.industry||[]).join(" · ")||"—")}</td></tr>`;}).join("")||`<tr><td colspan="9" class="empty">No headlines match the current filters.</td></tr>`}</tbody></table></section>`;}

function watchlist(model,ui){const rows=(model.opportunities||[]).filter(row=>ui.watchlist.has(row.symbol));return `<section class="panel watchlist-head"><div><span class="eyebrow">PRIVATE OWNER WATCHLIST</span><h2>${rows.length} pinned symbol${rows.length===1?"":"s"}</h2><p>Pinning never evicts an active V1 lifecycle commitment.</p></div><form id="watchlistAdd"><label>Add current radar symbol<select name="symbol"><option value="">Choose symbol</option>${model.opportunities.filter(row=>!ui.watchlist.has(row.symbol)).map(row=>`<option>${esc(row.symbol)}</option>`).join("")}</select></label><button>Add</button></form></section>${!model.watchlist_capacity?.monitoring_enabled?`<div class="capacity-warning"><strong>Monitoring capacity notice</strong><span>${esc(model.watchlist_capacity?.message||"A separate bounded provider lane is not enabled.")}</span></div>`:""}<section class="panel">${rows.length?radarTable(rows,{watchlist:ui.watchlist}):`<div class="empty-state"><strong>Your watchlist is empty.</strong><p>Add a symbol from the Opportunity Radar or use the control above.</p></div>`}</section>`;}

const TITLES={home:["LIVE OPPORTUNITY WORKSTATION","Home"],opportunities:["FULL FILTERED UNIVERSE","Opportunity Radar"],market:["BROAD CONTEXT · DESCRIPTIVE ONLY","Market Dashboard"],sectors:["PEER CONTEXT · NO ALIGNMENT GATE","Sectors & Industries"],news:["HEADLINE-ONLY EVIDENCE","News & Catalysts"],watchlist:["PRIVATE · OWNER ONLY","Watchlist"]};

export function renderWorkstation(doc,model,ui,now=Date.now()){
  const page=ROUTES.includes(ui.page)?ui.page:"home";const [eyebrow,title]=TITLES[page];
  doc.getElementById("pageEyebrow").textContent=eyebrow;doc.getElementById("pageTitle").textContent=title;
  doc.getElementById("demoBanner").hidden=!ui.demo;doc.getElementById("modeBadge").textContent=ui.demo?"SIMULATED":"READ ONLY";
  for(const link of doc.querySelectorAll("[data-route]")){link.classList.toggle("active",link.dataset.route===page);link.href=routeHref(link.dataset.route,ui.demo);}
  const status=dashboardStatus(model,now);doc.getElementById("snapshotTime").textContent=model?.as_of?`Snapshot ${dateTime(model.as_of)}`:"No snapshot";
  doc.getElementById("connection").textContent=ui.demo?"Isolated static demo":`${status.state}${finite(status.age)?` · ${Math.round(status.age)}s old`:""}`;
  const renderers={home,opportunities,market,sectors,news,watchlist};doc.getElementById("page").innerHTML=model?renderers[page](model,ui):`<section class="panel empty-state"><strong>Normalized live dashboard is not published yet.</strong><p>The authenticated site is healthy, but this projection predates the new read-only dashboard contract. Demo mode remains fully available at <a href="#/demo/home">#/demo</a>.</p></section>`;
}

export function renderDetail(doc,row,model=null){const overlay=doc.getElementById("detailOverlay");if(!row){overlay.hidden=true;doc.getElementById("detailDialog").replaceChildren();return;}overlay.hidden=false;doc.getElementById("detailDialog").innerHTML=detail(row,{model});}
