(()=>{"use strict";
const cfg=window.DASHBOARD_CONFIG_V34||{};
const $=id=>document.getElementById(id);
const VERSION="FUTURES_COMMAND_V34_EXECUTION_COMPANION_1_1_0";
if(!cfg.supabaseUrl||!cfg.supabasePublishableKey){document.body.innerHTML='<div class="auth-shell"><div class="auth-card"><h1>config_v34.js required</h1><p>Supabase publishable configuration is missing.</p></div></div>';return;}
const client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const POLL_MS=Math.max(30000,Number(cfg.pollSeconds||60)*1000),HEALTH_MAX_AGE_S=240,QUOTE_MAX_AGE_S=120;
const state={session:null,quotes:[],health:[],ema:[],nyBriefs:[],asiaBriefs:[],es5m:[],sessionView:"NY",marketSelection:{NY:null,ASIA:null},chart:null,series:null,priceLines:[],channel:null,realtime:"CONNECTING",lastFetch:null,fetching:false,journalLoaded:false,journalTrades:[],journalEvents:[],journalSelected:null};
window.FM_V34_CLIENT=client;window.FM_V34_STATE=state;

const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const n=(v,d=2)=>v===null||v===undefined||v===""||!Number.isFinite(Number(v))?"—":Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d});
const pct=v=>v===null||v===undefined||!Number.isFinite(Number(v))?"—":`${(Number(v)*100).toFixed(1)}%`;
const money=v=>!Number.isFinite(Number(v))?"—":`${Number(v)>0?"+":Number(v)<0?"-":""}$${Math.abs(Number(v)).toFixed(0)}`;
const dt=(v,withDate=false)=>{if(!v)return"—";try{return new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",...(withDate?{month:"short",day:"numeric"}:{}),hour:"numeric",minute:"2-digit",hour12:true}).format(new Date(v))+" CT";}catch{return"—";}};
const chartDate=t=>typeof t==="number"?new Date(t*1000):t&&typeof t==="object"&&Number.isFinite(Number(t.year))?new Date(Date.UTC(Number(t.year),Number(t.month)-1,Number(t.day))):new Date(t);
const chartTimeCt=t=>{try{return new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",month:"short",day:"numeric",hour:"numeric",minute:"2-digit",hour12:true}).format(chartDate(t))+" CT";}catch{return"—";}};
const chartTickCt=t=>{try{return new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",hour:"numeric",minute:"2-digit",hour12:true}).format(chartDate(t));}catch{return null;}};
const age=v=>{if(!v)return Infinity;const t=new Date(v).getTime();return Number.isFinite(t)?Math.max(0,(Date.now()-t)/1000):Infinity;};
const ageText=v=>{const s=age(v);if(!Number.isFinite(s))return"no timestamp";if(s<60)return`${Math.round(s)}s old`;if(s<3600)return`${Math.round(s/60)}m old`;return`${(s/3600).toFixed(1)}h old`;};
const latest=(arr,field)=>[...(arr||[])].sort((a,b)=>new Date(b?.[field]||0)-new Date(a?.[field]||0))[0]||null;
const quote=symbol=>(state.quotes||[]).filter(x=>x.symbol===symbol).sort((a,b)=>new Date(b.updated_at||b.timestamp)-new Date(a.updated_at||a.timestamp))[0]||null;
const service=name=>(state.health||[]).find(x=>x.service===name)||null;
const serviceLive=name=>{const x=service(name);return !!(x&&String(x.status).toUpperCase()==="LIVE"&&age(x.updated_at)<HEALTH_MAX_AGE_S);};
const toast=(msg,error=false)=>{const e=$("toast");if(!e)return;e.textContent=msg;e.className=`toast${error?" error":""}`;clearTimeout(toast._t);toast._t=setTimeout(()=>e.classList.add("hidden"),3200);};
async function q(label,promise){const {data,error}=await promise;if(error)throw new Error(`${label}: ${error.message}`);return data||[];}

function initialSession(){try{const saved=localStorage.getItem("v34-session");if(saved==="NY"||saved==="ASIA")return saved;}catch{}const h=Number(new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",hour:"2-digit",hourCycle:"h23"}).format(new Date()));return h>=8&&h<16?"NY":"ASIA";}
state.sessionView=initialSession();
function setSession(s){if(!["NY","ASIA"].includes(s))return;state.sessionView=s;try{localStorage.setItem("v34-session",s);}catch{}document.querySelectorAll("[data-session-toggle] button").forEach(b=>b.classList.toggle("active",b.dataset.session===s));$("sessionLabel").textContent=s==="NY"?"NY SESSION":"ASIA / GLOBEX";if(!state.session)return;renderBrief();renderMarketPage();renderTvSync();renderMap();}

function biasTone(v){const s=String(v||"").toUpperCase();return s.includes("BULL")?"good":s.includes("BEAR")?"bad":"neutral";}
function compactRegime(v){const s=String(v||"").toUpperCase(),out=[];if(s.includes("ROTAT")||s.includes("MEAN-REVERT")||s.includes("RANGE"))out.push("ROTATIONAL");else if(s.includes("TREND"))out.push("TRENDING");else if(s.includes("REVERS"))out.push("REVERSAL");else if(s.includes("BREAKOUT"))out.push("BREAKOUT");if(s.includes("MIXED")||s.includes("DIVERG"))out.push("MIXED");else if(s.includes("SQUEEZ"))out.push("SQUEEZE");else if(s.includes("REVERS")&&!out.includes("REVERSAL")&&out.length<2)out.push("REVERSAL");return(out.slice(0,2).join(" · ")||String(v||"—"));}
function selectedBriefList(){return state.sessionView==="NY"?state.nyBriefs:state.asiaBriefs;}
function selectedBrief(){const rows=selectedBriefList(),id=state.marketSelection[state.sessionView];return rows.find(x=>String(x.id)===String(id))||latest(rows,"brief_time");}
function latestSessionBrief(){return latest(selectedBriefList(),"brief_time");}
function sessionLevels(){const b=latestSessionBrief();if(!b)return[];if(state.sessionView==="NY")return(Array.isArray(b.levels)?b.levels:[]).map(x=>({...x,_src:"NY"}));return[...(Array.isArray(b.ny_carry_levels)?b.ny_carry_levels:[]).map(x=>({...x,_src:"NY CARRY"})),...(Array.isArray(b.asia_levels)?b.asia_levels:[]).map(x=>({...x,_src:"ASIA"}))];}
function levelRange(l){const lo=Number(l.mes_low??l.mes_level??l.mes_price),hi=Number(l.mes_high??l.mes_low??l.mes_level??l.mes_price);if(!Number.isFinite(lo))return null;return{lo,hi:Number.isFinite(hi)?hi:lo,mid:(lo+(Number.isFinite(hi)?hi:lo))/2};}
function levelKind(l){const x=`${l.type||""} ${l.status||""} ${l.label||""}`.toUpperCase();if(x.includes("RESIST"))return"R";if(x.includes("SUPPORT")||x.includes("RECLAIM"))return"S";return"P";}
function levelColor(l){const k=levelKind(l);if(k==="R")return"#ff6b78";if(k==="S")return"#44d19d";if(state.sessionView==="ASIA")return l._src==="NY CARRY"?"#62c7ff":"#a98cff";return"#f5bd59";}
function briefSummary(b){return b?.summary||b?.headline||"—";}
function levelPriority(l){const s=`${l.importance||""} ${l.type||""} ${l.label||""}`.toUpperCase();if(/MAJOR|CRITICAL|STRUCTURAL|SESSION HIGH|SESSION LOW|CASH OPEN|ATH|ACCEPTANCE|DECISION|BREAKOUT/.test(s))return 0;if(/PIVOT|RECLAIM|FAILED|PRIOR HIGH|PRIOR LOW/.test(s))return 1;return 2;}
function focusLabel(l){let s=String(l.label||l.type||l._src||"Market level").replace(/current\s+/ig,"").replace(/immediate\s+/ig,"").replace(/repeated\s+/ig,"").replace(/prior\s+cash-open/ig,"Cash open").replace(/prior\s+midday/ig,"Midday").replace(/current\s+session/ig,"Session").replace(/\s+/g," ").trim();return s.slice(0,42);}
function focusLevels(levels,price,maxShown=7){const rows=(levels||[]).map((l,i)=>({l,i,r:levelRange(l)})).filter(x=>x.r);if(!rows.length)return new Set();const px=Number(price),score=x=>(levelPriority(x.l)*4)+(Number.isFinite(px)?Math.abs(x.r.mid-px):0),selected=[];const add=x=>{if(!x||selected.includes(x))return;const duplicate=selected.some(y=>Math.abs(y.r.mid-x.r.mid)<=0.75||x.r.lo<=y.r.hi&&x.r.hi>=y.r.lo);if(!duplicate)selected.push(x);};if(Number.isFinite(px)){const inside=rows.filter(x=>px>=x.r.lo&&px<=x.r.hi).sort((a,b)=>score(a)-score(b))[0];add(inside);const above=rows.filter(x=>x.r.mid>px).sort((a,b)=>score(a)-score(b));const below=rows.filter(x=>x.r.mid<px).sort((a,b)=>score(a)-score(b));for(let i=0;i<Math.ceil((maxShown-selected.length)/2)&&i<above.length;i++)add(above[i]);for(let i=0;i<Math.floor((maxShown-selected.length)/2)+1&&i<below.length;i++)add(below[i]);}for(const x of [...rows].sort((a,b)=>score(a)-score(b)))if(selected.length<maxShown)add(x);return new Set(selected.slice(0,maxShown).map(x=>x.i));}

async function fetchEs5m(){const rows=await q("market_bars_live_es_5m",client.from("market_bars_live").select("bar_open_ms,bar_close_ms,payload").eq("data_type","ohlcv").eq("symbol","ES").eq("timeframe","5m").lte("bar_close_ms",Date.now()).order("bar_open_ms",{ascending:false}).limit(180));return[...rows].reverse().map(x=>{const p=x?.payload&&typeof x.payload==="object"?x.payload:{};return{bar_open_ms:Number(x.bar_open_ms),bar_close_ms:Number(x.bar_close_ms),open:Number(p.open),high:Number(p.high),low:Number(p.low),close:Number(p.close),volume:Number(p.volume||0)};}).filter(x=>[x.bar_open_ms,x.bar_close_ms,x.open,x.high,x.low,x.close].every(Number.isFinite));}
async function fetchCore(silent=false){if(!state.session||state.fetching)return;state.fetching=true;try{const [quotes,health,ema,ny,asia,es5m]=await Promise.all([
q("quotes",client.from("market_quotes_live").select("symbol,contract,bid,ask,last,timestamp,updated_at,source").in("symbol",["ES","MES"]).order("updated_at",{ascending:false}).limit(12)),
q("health",client.from("service_health").select("service,status,message,last_event_at,updated_at,metadata").in("service",["market_feed","ema_cci_v2_model"])),
q("ema",client.from("ema_cci_v2_events").select("event_id,root,contract,timeframe,session_scope,signal,direction,signal_close_utc,trading_day,gam_predicted_ev,gam_policy,entry_method,stop_method,target_r,v2_p_tp,v2_decision,base_quality,production_quality,v2_entry_proxy_price,planned_entry_price,planned_stop_price,planned_target_price,risk_points,execution_state,entry_valid_until,actual_fill_price,actual_stop_price,actual_target_price,filled_at,resolved_at,outcome,gam_sha256,v2_sha256,feature_version,model_inference_at,updated_at").eq("root","ES").order("signal_close_utc",{ascending:false}).limit(80)),
q("market_briefs",client.from("market_briefs").select("id,brief_time,session_date,daily_bias,prior_bias,bias_changed,regime,headline,summary,bullish_scenario,bearish_scenario,mes_spx_basis,basis_quote_time,levels,full_markdown,published_by,created_at,updated_at").order("brief_time",{ascending:false}).limit(8)),
q("market_briefs_asia",client.from("market_briefs_asia").select("*").order("brief_time",{ascending:false}).limit(8)),
fetchEs5m()
]);state.quotes=quotes;state.health=health;state.ema=ema;state.nyBriefs=ny;state.asiaBriefs=asia;state.es5m=es5m;for(const s of ["NY","ASIA"])if(state.marketSelection[s]&&!((s==="NY"?ny:asia).some(x=>String(x.id)===String(state.marketSelection[s]))))state.marketSelection[s]=null;state.lastFetch=new Date();renderAll();if(!silent)toast("V34 refreshed");}catch(err){console.error(err);toast(err.message,true);renderHealth(err);}finally{state.fetching=false;}}

function renderHealth(fetchError=null){const feedOk=serviceLive("market_feed"),emaOk=serviceLive("ema_cci_v2_model"),ready=feedOk&&emaOk&&!fetchError;const e=$("systemStatus");e.textContent=ready?"READY":"DEGRADED";e.className=`status-pill ${ready?"ready":"degraded"}`;const mes=quote("MES");$("mesHeader").textContent=mes?`MES ${n(mes.last)}`:"MES —";}

function renderBrief(){const b=latestSessionBrief(),card=$("briefCard");if(!b){card.className="panel hero-brief waiting";$("briefBias").textContent="Waiting for market brief";$("briefRegime").textContent="—";$("briefTime").textContent="—";$("briefSummary").textContent="—";$("briefBull").textContent="—";$("briefBear").textContent="—";$("briefFreshness").textContent="—";return;}const tone=biasTone(b.daily_bias);card.className=`panel hero-brief ${tone}`;$("briefBias").textContent=b.daily_bias||"NEUTRAL";$("briefRegime").textContent=compactRegime(b.regime||b.session_phase);$("briefRegime").className=`state-pill ${tone}`;$("briefTime").textContent=dt(b.brief_time,true);$("briefSummary").textContent=briefSummary(b);$("briefBull").textContent=b.bullish_scenario||"—";$("briefBear").textContent=b.bearish_scenario||"—";$("briefFreshness").textContent=`${state.sessionView} brief · ${ageText(b.updated_at||b.brief_time)}`;}

const unresolved=new Set(["WAIT_NEXT_BAR","WAIT_ENTRY","WORKING","OPEN","FILLED","ENTRY_PENDING","TRADE_CANDIDATE"]);
function activeEma(){return(state.ema||[]).find(x=>x.v2_decision==="TRADE"&&unresolved.has(String(x.execution_state||"").toUpperCase()))||null;}
function latestEma(tf){return(state.ema||[]).filter(x=>x.timeframe===tf).sort((a,b)=>new Date(b.signal_close_utc)-new Date(a.signal_close_utc))[0]||null;}
function emaTone(e){if(!e)return"";const s=String(e.execution_state||"").toUpperCase();if(s==="TP_HIT")return"won";if(s==="SL_HIT")return"lost";return e.v2_decision==="TRADE"?"trade":"";}
function renderModel(){const ok=serviceLive("ema_cci_v2_model"),e=activeEma(),pill=$("modelStatePill"),card=$("modelCard");pill.textContent=!ok?"STALE":e?"ACTIVE TRADE":"NO ACTIVE TRADE";pill.className=`state-pill ${!ok?"bad":e?"good":"neutral"}`;card?.classList.toggle("no-trade",!e);card?.classList.toggle("has-trade",!!e);if(e){const entry=e.actual_fill_price??e.planned_entry_price??e.v2_entry_proxy_price,sl=e.actual_stop_price??e.planned_stop_price,tp=e.actual_target_price??e.planned_target_price;$("modelHero").className="model-trade";$("modelHero").innerHTML=`<div class="model-cell hero"><span>Decision</span><strong>${esc(e.direction||"—")} · ${esc(String(e.timeframe||"").toUpperCase())}</strong><small>${esc(e.production_quality||"—")} · ${esc(String(e.execution_state||"TRADE").replaceAll("_"," "))}</small></div><div class="model-cell"><span>Entry</span><strong>${n(entry)}</strong></div><div class="model-cell"><span>Stop</span><strong>${n(sl)}</strong></div><div class="model-cell"><span>Target</span><strong>${n(tp)}</strong></div><div class="model-cell"><span>P(TP) / EV</span><strong>${pct(e.v2_p_tp)} · ${e.gam_predicted_ev===null?"—":Number(e.gam_predicted_ev).toFixed(2)+"R"}</strong></div>`;}else{const last=state.ema?.[0];$("modelHero").className="model-empty";$("modelHero").textContent=ok?(last?`No active trade · latest ${String(last.timeframe||"").toUpperCase()} ${last.direction||""} ${last.v2_decision||"—"} at ${dt(last.signal_close_utc)}`:"No active trade event."):"EMA model service is stale.";}
const tfs=["5m","10m","15m","1h"];$("modelTfStrip").innerHTML=tfs.map(tf=>{const x=latestEma(tf);if(!x)return`<span class="tf-pill">${tf.toUpperCase()} —</span>`;return`<span class="tf-pill ${emaTone(x)}">${tf.toUpperCase()} ${esc(x.direction||"—")} · ${esc(x.production_quality||x.v2_decision||"—")}</span>`;}).join("");const d=e||state.ema?.[0];$("modelDetailsBody").innerHTML=d?[["Signal",`${d.direction||"—"} ${d.signal||""}`],["Time",dt(d.signal_close_utc,true)],["Decision",d.v2_decision],["Quality",d.production_quality],["P(TP)",pct(d.v2_p_tp)],["Predicted EV",d.gam_predicted_ev===null?"—":Number(d.gam_predicted_ev).toFixed(4)+"R"],["Policy",d.gam_policy],["Entry method",d.entry_method],["Stop method",d.stop_method],["Target R",d.target_r===null?"—":n(d.target_r,1)+"R"],["Valid until",dt(d.entry_valid_until,true)],["Outcome",d.outcome||"—"]].map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v??"—")}</strong></div>`).join(""):"";}

function lineBreak3(rows,count=3){const src=[...(rows||[])].filter(x=>Number.isFinite(Number(x.time))&&Number.isFinite(Number(x.close))).sort((a,b)=>a.time-b.time);if(src.length<2)return[];let base=Number(src[0].close);const out=[];for(let i=1;i<src.length;i++){const s=src[i],close=Number(s.close);if(!out.length){if(close===base)continue;const direction=close>base?"up":"down",open=base;out.push({time:s.time,open,high:Math.max(open,close),low:Math.min(open,close),close,direction,projected:s.projected===true});continue;}const win=out.slice(-Math.max(1,Math.min(count,out.length))),hi=Math.max(...win.map(x=>Math.max(x.open,x.close))),lo=Math.min(...win.map(x=>Math.min(x.open,x.close)));const direction=close>hi?"up":close<lo?"down":null;if(!direction)continue;const last=out[out.length-1],open=direction===last.direction?last.close:last.open;out.push({time:s.time,open,high:Math.max(open,close),low:Math.min(open,close),close,direction,projected:s.projected===true});}return out;}
function lineBreakPlot(lines){return(lines||[]).map(x=>{const up=x.direction==="up",projected=x.projected===true,color=projected?(up?"#2f8d72":"#a74750"):(up?"#44d19d":"#ff6b78");return{time:x.time,open:x.open,high:x.high,low:x.low,close:x.close,color,borderColor:color,wickColor:color};});}
function lineBreakState(lines){if(!lines.length)return"WAITING";const d=lines[lines.length-1].direction;let run=0;for(let i=lines.length-1;i>=0&&lines[i].direction===d;i--)run++;return`${d==="up"?"BULLISH":"BEARISH"} ${run===1?"TRANSITION":"CONTINUATION"} · ${run} ${d==="up"?"GREEN":"RED"}`;}
function canonicalEsSource(){const data=(state.es5m||[]).map(b=>({time:Math.floor(b.bar_open_ms/1000),open:b.open,high:b.high,low:b.low,close:b.close}));const q=quote("ES"),price=Number(q?.last),ts=Date.parse(q?.timestamp||q?.updated_at||""),lastClose=Number(state.es5m[state.es5m.length-1]?.bar_close_ms);if(!Number.isFinite(price)||!Number.isFinite(ts)||!Number.isFinite(lastClose)||Date.now()-ts>QUOTE_MAX_AGE_S*1000||ts<lastClose)return data;const bucket=Math.floor(ts/300000)*300000,time=bucket/1000,last=data[data.length-1],open=Number.isFinite(last?.close)?last.close:price,i=data.findIndex(x=>x.time===time);if(i>=0){const b=data[i];data[i]={...b,high:Math.max(b.high,price),low:Math.min(b.low,price),close:price,projected:true};}else data.push({time,open,high:Math.max(open,price),low:Math.min(open,price),close:price,projected:true});return data;}
function ensureChart(){const el=$("marketMapChart");if(state.chart||!el||!window.LightweightCharts)return;state.chart=LightweightCharts.createChart(el,{layout:{background:{color:"#09131f"},textColor:"#8ea2b8"},grid:{vertLines:{color:"#122033"},horzLines:{color:"#122033"}},rightPriceScale:{borderColor:"#203247"},localization:{timeFormatter:chartTimeCt},timeScale:{borderColor:"#203247",timeVisible:true,secondsVisible:false,tickMarkFormatter:chartTickCt},crosshair:{mode:0}});state.series=state.chart.addSeries(LightweightCharts.CandlestickSeries,{upColor:"#44d19d",downColor:"#ff6b78",borderVisible:false,wickVisible:false,priceLineVisible:true,lastValueVisible:true});new ResizeObserver(()=>state.chart?.applyOptions({width:el.clientWidth,height:el.clientHeight})).observe(el);}
function renderMap(){ensureChart();if(!state.series)return;const keep=state.chart.timeScale().getVisibleLogicalRange(),source=canonicalEsSource(),lb=lineBreak3(source,3),data=lineBreakPlot(lb);state.series.setData(data);for(const l of state.priceLines)try{state.series.removePriceLine(l);}catch{}state.priceLines=[];const levels=sessionLevels(),mesPx=Number(quote("MES")?.last),focus=focusLevels(levels,mesPx,7);for(let i=0;i<levels.length;i++){const l=levels[i],r=levelRange(l);if(!r)continue;const isFocus=focus.has(i),base=levelColor(l),color=isFocus?base:"rgba(115,133,154,0.42)",width=isFocus?2:1,style=isFocus?(r.lo!==r.hi?2:0):2,title=isFocus?focusLabel(l):"";for(const p of [...new Set([r.lo,r.hi])])try{state.priceLines.push(state.series.createPriceLine({price:p,color,lineWidth:width,lineStyle:style,axisLabelVisible:isFocus,title}));}catch{}}if(keep)try{state.chart.timeScale().setVisibleLogicalRange(keep);}catch{}else if(data.length)state.chart.timeScale().fitContent();const b=latestSessionBrief();$("mapTitle").textContent=`${state.sessionView==="NY"?"NY Session":"Asia / Globex"} · 3-Line Break`;$("mapBriefTime").textContent=b?dt(b.brief_time,true):"WAITING";$("mapStatus").textContent=`Canonical ES 5m · ${data.length} lines · ${lineBreakState(lb)} · ${levels.length} total levels · ${focus.size} focus labels · live ES projection · Central Time (CT)`;}

function tvTick(v){return Math.round(Number(v)*4)/4;}
function tvNum(v){return Number.isFinite(Number(v))?tvTick(v).toFixed(2):"";}
function tvStatus(s){const x=String(s||"").toUpperCase();return x==="RECLAIMED"?"RC":x==="REJECTED"?"RJ":"A";}
function tvLabel(l){const prefix=state.sessionView==="ASIA"?(l._src==="NY CARRY"?"NY Carry ":"Asia "):"";return(prefix+String(l.label||l.type||"Market level")).replace(/[|,\r\n]+/g," / ").replace(/\s+/g," ").trim().slice(0,64);}
function tvHash(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0;}return`V${String(h%1000000).padStart(6,"0")}`;}
function buildTvPacket(){const levels=sessionLevels().map(l=>({l,r:levelRange(l)})).filter(x=>x.r).sort((a,b)=>b.r.mid-a.r.mid);if(!levels.length)return null;const records=levels.map(({l,r})=>`N,${tvNum(r.lo)},${tvNum(r.hi)},${levelKind(l)},${tvStatus(l.status)},${tvLabel(l)}`),body=records.join("|"),version=tvHash(`${state.sessionView}|${body}`);return{packet:`H,${version}|${body}`,version,count:records.length};}
async function copyText(text){if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return;}const ta=document.createElement("textarea");ta.value=text;ta.style.position="fixed";ta.style.opacity="0";document.body.appendChild(ta);ta.select();document.execCommand("copy");ta.remove();}
function syncKey(kind){return`v34-tv-${kind}-${state.sessionView}`;}
function renderTvSync(){const x=buildTvPacket(),status=$("tvSyncStatus"),meta=$("tvSyncMeta"),copy=$("tvCopyBtn"),mark=$("tvMarkBtn");$("tvSessionPill").textContent=state.sessionView;if(!x){status.textContent="Waiting for Market Map";status.className="tv-status changed";meta.textContent="No current MES Market Map levels.";copy.disabled=true;mark.classList.add("hidden");return;}copy.disabled=false;let synced=null,copied=null;try{synced=localStorage.getItem(syncKey("synced"));copied=localStorage.getItem(syncKey("copied"));}catch{}if(synced===x.version){status.textContent=`TradingView synced — ${x.version}`;status.className="tv-status synced";copy.textContent="COPY AGAIN";mark.classList.add("hidden");}else if(copied===x.version){status.textContent=`Copied ${x.version} — paste into TradingView`;status.className="tv-status copied";copy.textContent="COPY AGAIN";mark.classList.remove("hidden");mark.dataset.version=x.version;}else{status.textContent=`Levels changed — ${x.version}`;status.className="tv-status changed";copy.textContent="COPY NEW LEVELS";mark.classList.add("hidden");}copy.dataset.packet=x.packet;meta.textContent=`${x.count} ${state.sessionView} MES Market Map levels · Order Flow excluded`;}

function inlineMd(v){let x=esc(v||"");x=x.replace(/\[([^\]]+)\]\((https?:\/\/[^\s\)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');x=x.replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>");return x;}
function markdownTable(lines){const cells=line=>line.trim().replace(/^\||\|$/g,"").split("|").map(x=>x.trim()),head=cells(lines[0]),rows=lines.slice(2).map(cells);return`<div class="market-table-wrap"><table><thead><tr>${head.map(x=>`<th>${inlineMd(x)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${inlineMd(x)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;}
function markdownToHtml(md){const lines=String(md||"").replace(/\r/g,"").split("\n"),out=[];let i=0;while(i<lines.length){const l=lines[i];if(i+1<lines.length&&l.includes("|")&&/^\s*\|?\s*:?-+/.test(lines[i+1])){const t=[l,lines[i+1]];i+=2;while(i<lines.length&&lines[i].includes("|")&&lines[i].trim())t.push(lines[i++]);out.push(markdownTable(t));continue;}if(/^---+$/.test(l.trim())){out.push("<hr>");i++;continue;}const h=l.match(/^(#{1,3})\s+(.*)$/);if(h){out.push(`<h${h[1].length}>${inlineMd(h[2])}</h${h[1].length}>`);i++;continue;}if(/^\s*-\s+/.test(l)){const items=[];while(i<lines.length&&/^\s*-\s+/.test(lines[i]))items.push(lines[i++].replace(/^\s*-\s+/,""));out.push(`<ul>${items.map(x=>`<li>${inlineMd(x)}</li>`).join("")}</ul>`);continue;}if(!l.trim()){i++;continue;}const p=[l];i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,3})\s+/.test(lines[i])&&!/^\s*-\s+/.test(lines[i])&&!/^---+$/.test(lines[i].trim())&&!(i+1<lines.length&&lines[i].includes("|")&&/^\s*\|?\s*:?-+/.test(lines[i+1])))p.push(lines[i++]);out.push(`<p>${p.map(inlineMd).join("<br>")}</p>`);}return out.join("");}
function renderMarketPage(){const rows=selectedBriefList(),b=selectedBrief(),sel=$("marketArchive");sel.innerHTML=rows.length?rows.map(x=>`<option value="${esc(x.id)}" ${b&&String(x.id)===String(b.id)?"selected":""}>${dt(x.brief_time,true)} · ${esc(x.daily_bias||x.regime||"Update")}</option>`).join(""):'<option value="">No updates</option>';if(!b){$("marketSource").textContent="—";$("marketTitle").textContent="Waiting for brief";$("marketBody").innerHTML='<div class="empty-state">No market brief stored yet.</div>';$("marketRaw").textContent="—";return;}$("marketSource").textContent=`${state.sessionView} · ${String(b.published_by||"MARKET BRIEF").toUpperCase()}`;$("marketTitle").textContent=`${b.daily_bias||"—"} · ${b.regime||b.session_phase||"—"} · ${dt(b.brief_time,true)}`;const md=b.full_markdown||b.summary||b.headline||"";$("marketBody").innerHTML=markdownToHtml(md);$("marketRaw").textContent=md;}

function pnl(t){const p=Number(quote("MES")?.last),e=Number(t.avg_entry_price),qty=Number(t.open_contracts),s=t.direction==="LONG"?1:-1;return[p,e,qty].every(Number.isFinite)?s*(p-e)*qty*5:null;}
function journalTarget(t){const ev=(state.journalEvents||[]).filter(x=>x.trade_id===t.id).sort((a,b)=>new Date(b.event_time)-new Date(a.event_time)).find(x=>String(x.notes||"").startsWith("TARGET_UPDATE|"));const p=ev?Number(String(ev.notes).split("|")[1]):NaN;return Number.isFinite(p)?p:null;}
async function loadJournal(){if(!state.session)return;try{const [tr,ev]=await Promise.all([q("trades",client.from("trades").select("*").eq("instrument","MES").order("opened_at",{ascending:false}).limit(100)),q("trade_events",client.from("trade_events").select("*").order("event_time",{ascending:false}).limit(1000))]);state.journalTrades=tr;state.journalEvents=ev.filter(x=>tr.some(t=>t.id===x.trade_id));if(!state.journalSelected&&tr.length)state.journalSelected=tr.find(x=>x.status==="OPEN")?.id||tr[0].id;state.journalLoaded=true;renderJournal();}catch(err){console.error(err);toast(err.message,true);}}
async function rpc(name,p){const {data,error}=await client.rpc(name,p);if(error)throw error;return data;}
async function writeTarget(id,target){if(Number.isFinite(target))await rpc("add_trade_event",{p_trade_id:id,p_event_type:"NOTE",p_quantity:null,p_price:null,p_stop_price:null,p_reason:"MANUAL",p_notes:`TARGET_UPDATE|${target}`,p_market_snapshot_id:null,p_context:{target_price:target,source:"V34_EXECUTION_COMPANION"}});}
function renderJournal(){const host=$("journalMount");if(!host)return;if(!state.journalLoaded){host.innerHTML='<article class="panel"><div class="empty-state">Loading MES journal…</div></article>';return;}const open=state.journalTrades.filter(x=>x.status==="OPEN"),selected=state.journalTrades.find(x=>x.id===state.journalSelected);host.innerHTML=`<div class="journal-grid"><article class="panel"><div class="panel-head"><div><div class="eyebrow">NEW TRADE</div><h3>Record MES Fill</h3></div><small>Manual only</small></div><form id="journalNewForm" class="journal-form"><label>Side<select id="jDirection"><option>LONG</option><option>SHORT</option></select></label><label>Contracts<input id="jQty" type="number" min="1" value="1"></label><label>Entry<input id="jEntry" type="number" step="0.25" value="${Number.isFinite(Number(quote("MES")?.last))?Number(quote("MES").last).toFixed(2):""}"></label><label>Stop<input id="jStop" type="number" step="0.25"></label><label>Target<input id="jTarget" type="number" step="0.25"></label><button id="jUseLive" type="button" class="ghost">Use Live MES</button><button class="primary span2" type="submit">Open Journal Trade</button><div id="jError" class="error span2"></div></form></article><article class="panel"><div class="panel-head"><div><div class="eyebrow">OPEN POSITIONS</div><h3>${open.length} open</h3></div></div><div class="journal-positions">${open.length?open.map(t=>`<div class="trade-row" data-journal-trade="${esc(t.id)}"><div><span>MES ${esc(t.direction)}</span><strong>${t.open_contracts} @ ${n(t.avg_entry_price)}</strong></div><div><span>Live</span><strong>${n(quote("MES")?.last)}</strong></div><div><span>Open P/L</span><strong>${money(pnl(t))}</strong></div><div><span>Stop</span><strong>${n(t.current_stop_price)}</strong></div><div><span>Target</span><strong>${n(journalTarget(t))}</strong></div></div>`).join(""):'<div class="empty-state">No open MES trades.</div>'}</div></article></div>${selected?journalDetail(selected):""}<article class="panel" style="margin-top:14px"><div class="panel-head"><div><div class="eyebrow">RECENT</div><h3>MES Journal History</h3></div></div><div class="table-wrap"><table><thead><tr><th>Opened</th><th>Side</th><th>Status</th><th>Entry</th><th>Qty</th><th>Stop</th><th>Target</th><th>Realized</th></tr></thead><tbody>${state.journalTrades.map(t=>`<tr data-journal-trade="${esc(t.id)}"><td>${dt(t.opened_at,true)}</td><td>${esc(t.direction)}</td><td>${esc(t.status)}</td><td>${n(t.avg_entry_price)}</td><td>${t.open_contracts}</td><td>${n(t.current_stop_price)}</td><td>${n(journalTarget(t))}</td><td>${money(t.realized_pnl_dollars)}</td></tr>`).join("")}</tbody></table></div></article>`;}
function journalDetail(t){if(t.status!=="OPEN")return`<article class="panel" style="margin-top:14px"><div class="panel-head"><div><div class="eyebrow">SELECTED TRADE</div><h3>MES ${esc(t.direction)} · ${esc(t.status)}</h3></div><strong>${money(t.realized_pnl_dollars)}</strong></div></article>`;return`<article class="panel" style="margin-top:14px"><div class="panel-head"><div><div class="eyebrow">MANAGE SELECTED TRADE</div><h3>MES ${esc(t.direction)} · ${t.open_contracts} open</h3></div><strong>${money(pnl(t))}</strong></div><div class="manage-grid"><form id="jActionForm" class="manage-form"><strong>Position action</strong><label>Action<select id="jAction"><option value="TRIM">Trim</option><option value="TAKE_PROFIT">Take Profit</option><option value="SCALE_IN">Scale In</option><option value="EXIT">Exit Remaining</option></select></label><label>Qty<input id="jActionQty" type="number" min="1" value="1"></label><label>Fill<input id="jActionPrice" type="number" step="0.25" value="${Number.isFinite(Number(quote("MES")?.last))?Number(quote("MES").last).toFixed(2):""}"></label><button class="primary" type="submit">Save Action</button></form><form id="jStopForm" class="manage-form"><strong>Change stop</strong><label>New Stop<input id="jNewStop" type="number" step="0.25" value="${Number.isFinite(Number(t.current_stop_price))?Number(t.current_stop_price).toFixed(2):""}"></label><button class="ghost" type="submit">Save Stop</button></form><form id="jTargetForm" class="manage-form"><strong>Change target</strong><label>New Target<input id="jNewTarget" type="number" step="0.25" value="${Number.isFinite(Number(journalTarget(t)))?Number(journalTarget(t)).toFixed(2):""}"></label><button class="ghost" type="submit">Save Target</button></form></div></article>`;}
async function startJournalTrade(){const dir=$("jDirection").value,qty=Number($("jQty").value),entry=Number($("jEntry").value),stop=Number($("jStop").value),target=Number($("jTarget").value),err=$("jError");err.textContent="";if(!Number.isInteger(qty)||qty<=0||![entry,stop].every(Number.isFinite)){err.textContent="Enter valid MES trade details.";return;}if(dir==="LONG"?stop>=entry:stop<=entry){err.textContent="Stop is on the wrong side of entry.";return;}try{await rpc("start_trade",{p_instrument:"MES",p_direction:dir,p_entry_price:entry,p_stop_price:stop,p_contracts:qty,p_market_snapshot_id:null,p_entry_context:{source:"V34_EXECUTION_COMPANION",recorded_at:new Date().toISOString()},p_notes:null});await loadJournal();const t=state.journalTrades.find(x=>x.status==="OPEN"&&x.direction===dir);if(t&&Number.isFinite(target))await writeTarget(t.id,target);await loadJournal();toast("MES journal trade saved");}catch(x){err.textContent=x.message||"Could not save trade";}}
async function journalAction(){const t=state.journalTrades.find(x=>x.id===state.journalSelected);if(!t)return;const type=$("jAction").value,qty=Number($("jActionQty").value),price=Number($("jActionPrice").value);let eventType=type,reason="MANUAL",qv=qty;if(type==="TAKE_PROFIT"){eventType=qty>=Number(t.open_contracts)?"EXIT":"TRIM";reason="PRIMARY_TARGET";qv=eventType==="EXIT"?null:qty;}else if(type==="EXIT")qv=null;await rpc("add_trade_event",{p_trade_id:t.id,p_event_type:eventType,p_quantity:qv,p_price:price,p_stop_price:null,p_reason:reason,p_notes:null,p_market_snapshot_id:null,p_context:{source:"V34_EXECUTION_COMPANION"}});await loadJournal();}
async function journalStop(){const t=state.journalTrades.find(x=>x.id===state.journalSelected),p=Number($("jNewStop").value);if(!t||!Number.isFinite(p))return;await rpc("add_trade_event",{p_trade_id:t.id,p_event_type:"STOP_UPDATE",p_quantity:null,p_price:null,p_stop_price:p,p_reason:"STRUCTURE_UPDATE",p_notes:null,p_market_snapshot_id:null,p_context:{source:"V34_EXECUTION_COMPANION"}});await loadJournal();}
async function journalTargetUpdate(){const t=state.journalTrades.find(x=>x.id===state.journalSelected),p=Number($("jNewTarget").value);if(!t||!Number.isFinite(p))return;await writeTarget(t.id,p);await loadJournal();}

function renderDiagnostics(){const b=latestSessionBrief(),es=quote("ES"),mes=quote("MES");$("diagnosticsBody").innerHTML=[["Version",VERSION],["Market feed",`${service("market_feed")?.status||"—"} · ${ageText(service("market_feed")?.updated_at)}`],["EMA model",`${service("ema_cci_v2_model")?.status||"—"} · ${ageText(service("ema_cci_v2_model")?.updated_at)}`],["Realtime",state.realtime],["ES quote",`${n(es?.last)} · ${ageText(es?.updated_at||es?.timestamp)}`],["MES quote",`${n(mes?.last)} · ${ageText(mes?.updated_at||mes?.timestamp)}`],[`${state.sessionView} brief`,b?`${dt(b.brief_time,true)} · ${ageText(b.updated_at||b.brief_time)}`:"—"],["Canonical ES 5m",`${state.es5m.length} bars`],["EMA events",String(state.ema.length)],["Last full fetch",state.lastFetch?dt(state.lastFetch.toISOString(),true):"—"],["Browser poll",`${POLL_MS/1000}s`],["Order Flow","Excluded from V34"]].map(([k,v])=>`<div class="diag"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join("");}
function renderAll(){renderHealth();renderBrief();renderModel();renderTvSync();renderMarketPage();renderMap();renderDiagnostics();if(state.journalLoaded)renderJournal();}

function mergeBy(arr,row,key,sortField,limit){const k=key(row),prev=arr.find(x=>key(x)===k);let out=arr.filter(x=>key(x)!==k);out.push({...prev,...row});if(sortField)out.sort((a,b)=>new Date(b?.[sortField]||0)-new Date(a?.[sortField]||0));return limit?out.slice(0,limit):out;}
function parseMarketBar(row){if(row?.data_type!=="ohlcv"||row?.symbol!=="ES"||row?.timeframe!=="5m")return null;const p=row.payload&&typeof row.payload==="object"?row.payload:{};const x={bar_open_ms:Number(row.bar_open_ms),bar_close_ms:Number(row.bar_close_ms),open:Number(p.open),high:Number(p.high),low:Number(p.low),close:Number(p.close),volume:Number(p.volume||0)};return[x.bar_open_ms,x.bar_close_ms,x.open,x.high,x.low,x.close].every(Number.isFinite)?x:null;}
function applyRealtime(table,payload){const row=payload?.new;if(!row)return;try{if(table==="market_quotes_live"){if(!["ES","MES"].includes(row.symbol))return;state.quotes=state.quotes.filter(x=>x.symbol!==row.symbol);state.quotes.unshift(row);renderHealth();renderMap();if(state.journalLoaded)renderJournal();return;}if(table==="service_health"){if(!["market_feed","ema_cci_v2_model"].includes(row.service))return;state.health=mergeBy(state.health,row,x=>x.service,"updated_at");renderHealth();renderModel();return;}if(table==="ema_cci_v2_events"){if(row.root!=="ES")return;state.ema=mergeBy(state.ema,row,x=>x.event_id,"signal_close_utc",80);renderModel();return;}if(table==="market_briefs"){state.nyBriefs=mergeBy(state.nyBriefs,row,x=>x.id,"brief_time",8);renderBrief();renderMarketPage();renderTvSync();renderMap();return;}if(table==="market_briefs_asia"){state.asiaBriefs=mergeBy(state.asiaBriefs,row,x=>x.id,"brief_time",8);renderBrief();renderMarketPage();renderTvSync();renderMap();return;}if(table==="market_bars_live"){const b=parseMarketBar(row);if(!b)return;state.es5m=state.es5m.filter(x=>x.bar_open_ms!==b.bar_open_ms);state.es5m.push(b);state.es5m.sort((a,c)=>a.bar_open_ms-c.bar_open_ms);if(state.es5m.length>180)state.es5m=state.es5m.slice(-180);renderMap();}}catch(err){console.error("Realtime apply failed",table,err);}}
function subscribe(){if(state.channel){client.removeChannel(state.channel);state.channel=null;}state.realtime="CONNECTING";const tables=["market_quotes_live","service_health","ema_cci_v2_events","market_briefs","market_briefs_asia","market_bars_live"];let ch=client.channel("v34-live");for(const table of tables)ch=ch.on("postgres_changes",{event:"*",schema:"public",table},payload=>applyRealtime(table,payload));state.channel=ch.subscribe(status=>{state.realtime=status;renderHealth();renderDiagnostics();});}

function showTab(name){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===name));document.querySelectorAll(".tab-panel").forEach(x=>x.classList.toggle("active",x.id===`tab-${name}`));if(name==="today")setTimeout(renderMap,30);if(name==="journal"&&!state.journalLoaded)void loadJournal();}
function wire(){document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>showTab(b.dataset.tab)));document.querySelectorAll("[data-goto]").forEach(b=>b.addEventListener("click",()=>showTab(b.dataset.goto)));document.querySelectorAll("[data-session-toggle] button").forEach(b=>b.addEventListener("click",()=>setSession(b.dataset.session)));$("refreshBtn").addEventListener("click",()=>fetchCore());$("signOutBtn").addEventListener("click",()=>client.auth.signOut());$("diagnosticsBtn").addEventListener("click",()=>{$("diagnosticsModal").classList.remove("hidden");renderDiagnostics();});document.addEventListener("click",e=>{if(e.target.closest("[data-close-diagnostics]"))$("diagnosticsModal").classList.add("hidden");const tr=e.target.closest("[data-journal-trade]");if(tr){state.journalSelected=tr.dataset.journalTrade;renderJournal();}if(e.target.closest("#jUseLive")){const p=Number(quote("MES")?.last);if(Number.isFinite(p))$("jEntry").value=p.toFixed(2);}});document.addEventListener("keydown",e=>{if(e.key==="Escape")$("diagnosticsModal").classList.add("hidden");});$("marketArchive").addEventListener("change",e=>{state.marketSelection[state.sessionView]=e.target.value||null;renderMarketPage();});$("tvCopyBtn").addEventListener("click",async()=>{const x=buildTvPacket();if(!x)return;try{await copyText(x.packet);localStorage.setItem(syncKey("copied"),x.version);renderTvSync();}catch(err){console.error(err);toast("Could not copy TradingView levels",true);}});$("tvMarkBtn").addEventListener("click",()=>{const x=buildTvPacket();if(!x)return;try{localStorage.setItem(syncKey("synced"),x.version);}catch{}renderTvSync();});$("journalRefresh").addEventListener("click",()=>loadJournal());document.addEventListener("submit",async e=>{try{if(e.target.id==="journalNewForm"){e.preventDefault();await startJournalTrade();}else if(e.target.id==="jActionForm"){e.preventDefault();await journalAction();}else if(e.target.id==="jStopForm"){e.preventDefault();await journalStop();}else if(e.target.id==="jTargetForm"){e.preventDefault();await journalTargetUpdate();}}catch(err){console.error(err);toast(err.message||"Journal update failed",true);}},true);$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginError").textContent="";const {data,error}=await client.auth.signInWithPassword({email:$("loginEmail").value.trim(),password:$("loginPassword").value});if(error){$("loginError").textContent=error.message;return;}await show(data.session);});}
async function show(session){state.session=session;$("authShell").classList.toggle("hidden",!!session);$("appShell").classList.toggle("hidden",!session);if(session){await fetchCore(true);subscribe();setSession(state.sessionView);}else if(state.channel){client.removeChannel(state.channel);state.channel=null;}}
wire();setSession(state.sessionView);setInterval(()=>{$("clock").textContent=new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",weekday:"short",hour:"numeric",minute:"2-digit",second:"2-digit",hour12:true}).format(new Date())+" CT";renderHealth();},1000);setInterval(()=>{if(state.session)void fetchCore(true);},POLL_MS);setInterval(()=>{if(state.journalLoaded&&$("tab-journal").classList.contains("active"))void loadJournal();},30000);client.auth.getSession().then(({data})=>show(data.session));client.auth.onAuthStateChange((_event,session)=>{if(session!==state.session)void show(session);});
})();
