(()=>{"use strict";
const cfg=window.DASHBOARD_CONFIG||{};
const $=id=>document.getElementById(id);
if(!cfg.supabaseUrl||!cfg.supabasePublishableKey){document.body.innerHTML='<div class="auth-shell"><div class="auth-card"><h1>config.js required</h1><p>Supabase publishable configuration is missing.</p></div></div>';return;}
const client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const VERSION="FUTURES_COMMAND_V33_ES_ONLY_1_0_1_REMOTE_MERGE";
const OF_MAX_AGE_S=120, LEGACY_MAX_AGE_S=240, POLL_SECONDS=Number(cfg.pollSeconds), POLL_MS=(Number.isFinite(POLL_SECONDS)&&POLL_SECONDS>=30?POLL_SECONDS:60)*1000, PAGE_SIZE=1000;
const state={session:null,quotes:[],health:[],emaEvents:[],ofHealth:null,models:[],contracts:[],levels:[],events:[],rawBars:[],bars:[],footprints:[],briefs:[],selectedBriefId:null,tf:"5m",chart:null,candles:null,priceLines:[],channel:null,realtime:"CONNECTING",lastFetch:null,fetching:false,debounce:null};
window.FM_V33_CLIENT=client;window.FM_V33_STATE=state;
function n(v,d=2){if(v===null||v===undefined||v===""||!Number.isFinite(Number(v)))return "—";return Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d});}
function pct(v){return v===null||v===undefined||!Number.isFinite(Number(v))?"—":`${(Number(v)*100).toFixed(1)}%`;}
function shortHash(v){return v?`${String(v).slice(0,10)}…${String(v).slice(-6)}`:"—";}
function dt(v,withDate=false){if(!v)return "—";const d=new Date(v);if(Number.isNaN(d.getTime()))return "—";return new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",month:withDate?"short":undefined,day:withDate?"numeric":undefined,hour:"numeric",minute:"2-digit",second:withDate?undefined:undefined,hour12:true}).format(d)+" CT";}
function age(v){if(!v)return Infinity;const ms=Date.now()-new Date(v).getTime();return Math.max(0,ms/1000);}
function ageText(v){const s=age(v);if(!Number.isFinite(s))return "no heartbeat";if(s<60)return `${Math.round(s)}s old`;if(s<3600)return `${Math.round(s/60)}m old`;return `${(s/3600).toFixed(1)}h old`;}
function setText(id,v){const e=$(id);if(e)e.textContent=v??"—";}
function badge(id,text,kind){const e=$(id);if(!e)return;e.textContent=text;e.className=`badge ${kind}`;}
function pill(id,text,kind="neutral"){const e=$(id);if(!e)return;e.textContent=text;e.className=`state-pill ${kind}`;}
function toast(msg,isErr=false){const e=$("toast");e.textContent=msg;e.className=`toast${isErr?" error":""}`;clearTimeout(toast._t);toast._t=setTimeout(()=>e.classList.add("hidden"),4500);}
function safeMeta(o){return o&&typeof o==="object"?o:{};}
function latestBySymbol(symbol){return state.quotes.filter(x=>x.symbol===symbol).sort((a,b)=>new Date(b.updated_at||b.timestamp)-new Date(a.updated_at||a.timestamp))[0]||null;}
function service(name){return state.health.find(x=>x.service===name)||null;}
function liveService(name){const s=service(name);return !!(s&&String(s.status).toUpperCase()==="LIVE"&&age(s.updated_at)<LEGACY_MAX_AGE_S);}
function servingGate(){const h=state.ofHealth,m=safeMeta(h?.metadata),scope=Array.isArray(m.production_scope)?m.production_scope.map(String):[];return !!(h&&String(h.status).toUpperCase()==="LIVE"&&h.scoring_enabled===true&&age(h.updated_at)<OF_MAX_AGE_S&&m.supabase_publication_enabled===true&&m.website_serving_enabled===true&&m.nq_mnq_retired===true&&scope.length===2&&scope.includes("ES")&&scope.includes("MES"));}
async function q(label,promise){const {data,error}=await promise;if(error)throw new Error(`${label}: ${error.message}`);return data||[];}
async function fetchLevelsPaged(){let out=[],from=0;for(;;){const rows=await q("orderflow_levels",client.from("orderflow_levels").select("level_id,root,contract,level_type,level_family,reference_price,zone_low,zone_high,approach_side,test_number,active,state,watch_probability,standard_probability,available_at,last_touch_at,metadata,updated_at").eq("root","ES").eq("active",true).order("reference_price",{ascending:true}).order("level_id",{ascending:true}).range(from,from+PAGE_SIZE-1));out.push(...rows);if(rows.length<PAGE_SIZE)break;from+=rows.length;if(from>20000)throw new Error("active level pagination exceeded safety cap");}return out;}
function aggregateCompleted5m(rows){const groups=new Map();for(const b of rows){const open=Number(b.bar_open_ms),close=Number(b.bar_close_ms);if(!Number.isFinite(open)||!Number.isFinite(close))continue;const bucket=Math.floor(open/300000)*300000;if(!groups.has(bucket))groups.set(bucket,[]);groups.get(bucket).push(b);}const out=[];for(const [bucket,g] of [...groups.entries()].sort((a,b)=>a[0]-b[0])){g.sort((a,b)=>Number(a.bar_open_ms)-Number(b.bar_open_ms));const expected=[0,60000,120000,180000,240000].map(x=>bucket+x);const opens=g.map(x=>Number(x.bar_open_ms));if(g.length!==5||!expected.every((x,i)=>opens[i]===x)||Number(g[4].bar_close_ms)!==bucket+300000)continue;out.push({contract:g[0].contract,timeframe:"5m",bar_open_ms:bucket,bar_close_ms:bucket+300000,open:Number(g[0].open),high:Math.max(...g.map(x=>Number(x.high))),low:Math.min(...g.map(x=>Number(x.low))),close:Number(g[4].close),volume:g.reduce((a,x)=>a+Number(x.volume||0),0),delta:g.reduce((a,x)=>a+Number(x.delta||0),0)});}return out;}
function setDisplayBars(){state.bars=state.tf==="1m"?[...state.rawBars]:aggregateCompleted5m(state.rawBars);}
async function fetchAll(silent=false){if(!state.session||state.fetching)return;state.fetching=true;try{
  const [quotes,health,ema,ofh,models,contracts,levels,events,footprints,briefs]=await Promise.all([
    q("market_quotes_live",client.from("market_quotes_live").select("symbol,contract,bid,ask,last,timestamp,updated_at,source").in("symbol",["ES","MES"]).order("updated_at",{ascending:false}).limit(20)),
    q("service_health",client.from("service_health").select("service,status,message,last_event_at,updated_at,metadata").in("service",["market_feed","market_footprint","ema_cci_v2_model"])),
    q("ema_cci_v2_events",client.from("ema_cci_v2_events").select("event_id,root,contract,timeframe,session_scope,signal,direction,signal_close_utc,trading_day,gam_predicted_ev,gam_policy,entry_method,stop_method,target_r,v2_p_tp,v2_decision,base_quality,production_quality,v2_entry_proxy_price,planned_entry_price,planned_stop_price,planned_target_price,risk_points,execution_state,entry_valid_until,actual_fill_price,actual_stop_price,actual_target_price,filled_at,resolved_at,outcome,gam_sha256,v2_sha256,feature_version,model_inference_at,updated_at").eq("root","ES").order("signal_close_utc",{ascending:false}).limit(120)),
    q("orderflow_service_health",client.from("orderflow_service_health").select("*").eq("service","orderflow_fastpath").limit(1)),
    q("orderflow_model_state",client.from("orderflow_model_state").select("*").eq("root","ES").order("role",{ascending:true})),
    q("orderflow_contract_state",client.from("orderflow_contract_state").select("*").in("symbol",["ES","MES"]).order("symbol",{ascending:true})),
    fetchLevelsPaged(),
    q("orderflow_events",client.from("orderflow_events").select("event_id,role,root,contract,level_id,level_type,level_family,reference_price,test_number,decision_time,state,breakout_probability,rejection_probability,feature_version,model_sha256,calibrator_sha256,metadata,updated_at").eq("root","ES").order("decision_time",{ascending:false}).limit(500)),
    q("orderflow_footprint_cache",client.from("orderflow_footprint_cache").select("contract,bar_open_ms,bar_close_ms,ladder,row_count,source,updated_at").order("bar_open_ms",{ascending:false}).limit(12)),
    q("market_briefs",client.from("market_briefs").select("id,brief_time,session_date,daily_bias,prior_bias,bias_changed,regime,headline,summary,bullish_scenario,bearish_scenario,mes_spx_basis,basis_quote_time,levels,full_markdown,published_by,created_at,updated_at").order("brief_time",{ascending:false}).limit(8))
  ]);
  state.quotes=quotes;state.health=health;state.emaEvents=ema;state.ofHealth=ofh[0]||null;state.models=models;state.contracts=contracts;state.levels=levels;state.events=events;state.footprints=footprints;state.briefs=briefs;if(!state.selectedBriefId&&briefs[0])state.selectedBriefId=briefs[0].id;
  const esContract=(contracts.find(x=>x.symbol==="ES"&&x.contract_role==="CURRENT")||{}).contract;
  state.rawBars=esContract?await q("orderflow_chart_bars",client.from("orderflow_chart_bars").select("contract,timeframe,bar_open_ms,bar_close_ms,open,high,low,close,volume,delta,updated_at").eq("contract",esContract).eq("timeframe","1m").order("bar_open_ms",{ascending:true}).limit(600)):[];
  setDisplayBars();
  state.lastFetch=new Date();renderAll();if(!silent)toast("V33 refreshed");
}catch(e){console.error(e);toast(e.message,true);renderSystem(true,e.message);}finally{state.fetching=false;}}
function renderSystem(fetchError=false,msg=""){
  const feedOk=liveService("market_feed"),emaOk=liveService("ema_cci_v2_model"),ofOk=servingGate();
  badge("feedBadge",feedOk?"FEED LIVE":"FEED STALE",feedOk?"live":"bad");
  badge("emaBadge",emaOk?"EMA/CCI LIVE":"EMA/CCI STALE",emaOk?"live":"bad");
  badge("ofBadge",ofOk?"ORDER FLOW LIVE":(state.ofHealth?"ORDER FLOW PARKED":"ORDER FLOW UNAVAILABLE"),ofOk?"live":"waiting");
  badge("rtBadge",state.realtime==="SUBSCRIBED"?"REALTIME LIVE":"REALTIME FALLBACK",state.realtime==="SUBSCRIBED"?"live":"waiting");
  const banner=$("systemBanner");
  const all=feedOk&&emaOk&&ofOk&&!fetchError;
  banner.className=`system-banner ${all?"live":fetchError?"bad":"waiting"}`;
  banner.querySelector("strong").textContent=all?"PRODUCTION GATES LIVE":fetchError?"DATA REFRESH ERROR":"FAIL-CLOSED / PARTIAL AVAILABILITY";
  banner.querySelector("span").textContent=all?"Frozen strategy decisions and validated Order Flow serving are fresh.":fetchError?msg:"Any unavailable component is parked independently; stale probabilities are not actionable.";
}
function renderQuotes(){for(const sym of ["ES","MES"]){const x=latestBySymbol(sym);setText(sym.toLowerCase()+"Last",x?n(x.last):"—");setText(sym.toLowerCase()+"Contract",x?.contract||"—");setText(sym.toLowerCase()+"QuoteAge",x?ageText(x.updated_at||x.timestamp):"—");}
  setText("activeLevelCount",state.levels.length.toLocaleString());const es=latestBySymbol("ES"),px=Number(es?.last);const sorted=sortedLevels(px);const nearest=sorted[0];setText("nearestLevelSummary",nearest&&Number.isFinite(px)?`${nearest.level_type} @ ${n(nearest.reference_price)} · ${n(Math.abs(Number(nearest.reference_price)-px))} pts`:"—");
  const h=state.ofHealth,m=safeMeta(h?.metadata);setText("publishCutoff",m.published_cutoff?dt(m.published_cutoff):"—");setText("publisherVersion",m.publisher_version||"—");setText("healthAge",h?ageText(h.updated_at):"—");}
function currentEma(){const unresolved=new Set(["WAIT_NEXT_BAR","WAIT_ENTRY","WORKING","OPEN","FILLED","ENTRY_PENDING"]);return state.emaEvents.find(x=>x.v2_decision==="TRADE"&&unresolved.has(String(x.execution_state||"").toUpperCase()))||state.emaEvents.find(x=>x.v2_decision==="TRADE")||state.emaEvents[0]||null;}
function renderEma(){const e=currentEma(),ok=liveService("ema_cci_v2_model");if(!e){pill("emaDecisionPill","NO EVENT");return;}const isTrade=e.v2_decision==="TRADE";pill("emaDecisionPill",ok?(isTrade?e.execution_state||"TRADE":"SKIP"):"STALE",ok&&isTrade?"good":ok?"neutral":"bad");setText("emaDirection",e.direction||"—");setText("emaSignalMeta",`${e.timeframe||"—"} · ${e.signal||"—"} · ${dt(e.signal_close_utc,true)}`);setText("emaV2Decision",e.v2_decision||"—");setText("emaQuality",`Quality ${e.production_quality||"—"}`);setText("emaPtp",pct(e.v2_p_tp));setText("emaEv",e.gam_predicted_ev===null?"—":Number(e.gam_predicted_ev).toFixed(3)+"R");const entry=e.actual_fill_price??e.planned_entry_price??e.v2_entry_proxy_price;setText("emaEntry",n(entry));setText("emaEntryMethod",e.actual_fill_price?`Filled ${dt(e.filled_at)}`:(e.entry_method||"—"));setText("emaStop",n(e.actual_stop_price??e.planned_stop_price));setText("emaStopMethod",e.stop_method||"—");setText("emaTarget",n(e.actual_target_price??e.planned_target_price));setText("emaTargetR",e.target_r!==null&&e.target_r!==undefined?`${n(e.target_r,1)}R target`:"—");setText("emaRisk",e.risk_points!==null&&e.risk_points!==undefined?`${n(e.risk_points)} pts`:"—");setText("emaExpiry",e.entry_valid_until?`Valid to ${dt(e.entry_valid_until)}`:"—");const note=$("emaDecisionNote");note.className=`decision-note ${ok&&isTrade?"good":!ok?"bad":""}`;note.textContent=!ok?"EMA/CCI service is stale or stopped. Frozen event data is shown for audit only.":isTrade?`Frozen TRADE decision · ${e.gam_policy||"policy —"} · execution ${e.execution_state||"—"}.`:"Latest frozen decision is SKIP; no entry should be inferred by the browser.";}
function model(role){return state.models.find(x=>x.role===role)||null;}
function renderModel(role,prefix){const m=model(role);setText(prefix+"Level",m?`${n(m.reference_price)} ${m.level_family||""}`:"—");setText(prefix+"LevelType",m?.level_type||"—");setText(prefix+"Reject",pct(m?.rejection_probability));setText(prefix+"Break",pct(m?.breakout_probability));setText(prefix+"State",m?.state||"—");setText(prefix+"Time",m?.decision_time?dt(m.decision_time):"—");}
function clearModel(prefix){for(const k of ["Level","LevelType","Reject","Break","Time"])setText(prefix+k,"—");setText(prefix+"State","PARKED");}
function renderOrderFlow(){const ok=servingGate();pill("ofServingPill",ok?"LIVE":"PARKED",ok?"good":"neutral");if(ok){renderModel("WATCH","watch");renderModel("STANDARD","standard");}else{clearModel("watch");clearModel("standard");}const note=$("ofDecisionNote");note.className=`decision-note ${ok?"good":"bad"}`;note.textContent=ok?"Validated Supabase publisher + serving gate are LIVE. Probabilities are frozen server outputs.":"Order Flow is fail-closed. Main decision probabilities are hidden until remote serving health is LIVE and fresh; historical rows remain available only in the audit/event views.";}
function sortedLevels(px){const rows=[...state.levels];if(Number.isFinite(px))rows.sort((a,b)=>Math.abs(Number(a.reference_price)-px)-Math.abs(Number(b.reference_price)-px));return rows;}
function renderNearest(){const px=Number(latestBySymbol("ES")?.last),rows=sortedLevels(px).slice(0,10);$("nearestLevels").innerHTML=rows.length?rows.map(r=>{const d=Number.isFinite(px)?Number(r.reference_price)-px:null;const rp=r.standard_probability??r.watch_probability;return `<div class="nearest-row"><span class="distance">${d===null?"—":`${d>=0?"+":""}${n(d)}`}</span><span class="price">${n(r.reference_price)}</span><span>${esc(r.level_type)} <small class="muted">${esc(r.level_family)}</small></span><span class="prob">${rp===null||rp===undefined?"—":pct(1-Number(rp))} rej</span></div>`}).join(""):"<div class='muted'>No active levels loaded.</div>";}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function latestBrief(){return [...state.briefs].sort((a,b)=>new Date(b.brief_time)-new Date(a.brief_time))[0]||null;}
function chosenBrief(){return state.briefs.find(x=>x.id===state.selectedBriefId)||latestBrief();}
function biasTone(v){const s=String(v||"").toUpperCase();return s.includes("BULL")?"good":s.includes("BEAR")?"bad":"neutral";}
function inlineMd(v){let x=esc(v||"");x=x.replace(/\[([^\]]+)\]\((https?:\/\/[^\s\)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');x=x.replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>");return x;}
function markdownTable(lines){const cells=line=>line.trim().replace(/^\||\|$/g,"").split("|").map(x=>x.trim());const head=cells(lines[0]),rows=lines.slice(2).map(cells);return `<div class="market-table-wrap"><table class="market-table"><thead><tr>${head.map(x=>`<th>${inlineMd(x)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${inlineMd(x)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;}
function markdownToHtml(md){const lines=String(md||"").replace(/\r/g,"").split("\n"),out=[];let i=0;while(i<lines.length){const l=lines[i];if(i+1<lines.length&&l.includes("|")&&/^\s*\|?\s*:?-+/.test(lines[i+1])){const t=[l,lines[i+1]];i+=2;while(i<lines.length&&lines[i].includes("|")&&lines[i].trim())t.push(lines[i++]);out.push(markdownTable(t));continue;}if(/^---+$/.test(l.trim())){out.push("<hr>");i++;continue;}const h=l.match(/^(#{1,3})\s+(.*)$/);if(h){const n=h[1].length;out.push(`<h${n}>${inlineMd(h[2])}</h${n}>`);i++;continue;}if(/^\s*-\s+/.test(l)){const items=[];while(i<lines.length&&/^\s*-\s+/.test(lines[i]))items.push(lines[i++].replace(/^\s*-\s+/,""));out.push(`<ul>${items.map(x=>`<li>${inlineMd(x)}</li>`).join("")}</ul>`);continue;}if(!l.trim()){i++;continue;}const p=[l];i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,3})\s+/.test(lines[i])&&!/^\s*-\s+/.test(lines[i])&&!/^---+$/.test(lines[i].trim())&&!(i+1<lines.length&&lines[i].includes("|")&&/^\s*\|?\s*:?-+/.test(lines[i+1])))p.push(lines[i++]);out.push(`<p>${p.map(inlineMd).join("<br>")}</p>`);}return out.join("");}
function renderBrief(){const b=latestBrief(),card=$("briefCard");if(!card)return;if(!b){card.className="panel brief-card waiting";setText("briefBias","Waiting for market update");setText("briefTime","—");setText("briefRegime","—");setText("briefSummary","No hourly brief stored yet.");setText("briefBull","—");setText("briefBear","—");setText("briefSource","—");return;}const tone=biasTone(b.daily_bias);card.className=`panel brief-card ${tone}`;setText("briefBias",b.daily_bias||"—");setText("briefTime",dt(b.brief_time,true));setText("briefRegime",b.regime||"—");setText("briefSummary",b.summary||b.headline||"—");setText("briefBull",b.bullish_scenario||"—");setText("briefBear",b.bearish_scenario||"—");setText("briefSource",`${b.published_by||"market_briefs"} · ${ageText(b.updated_at||b.brief_time)}`);$("briefChanged")?.classList.toggle("hidden",!b.bias_changed);}
function renderMarketUpdate(){const b=chosenBrief();if(!b){$("marketUpdateBody").innerHTML='<div class="empty-state">No market update stored yet.</div>';$("marketUpdateRaw").textContent="No market update stored yet.";$("marketUpdateArchive").innerHTML="";$("marketMesLevels").innerHTML='<div class="empty-state">No hourly levels stored yet.</div>';return;}setText("marketUpdateTime",dt(b.brief_time,true));const bp=$("marketUpdateBias");bp.textContent=b.daily_bias||"—";bp.className=`state-pill ${biasTone(b.daily_bias)}`;setText("marketUpdateRegime",b.regime||"—");setText("marketUpdateSource",String(b.published_by||"HOURLY UPDATE").toUpperCase());const md=b.full_markdown||b.summary||"";$("marketUpdateBody").innerHTML=markdownToHtml(md);$("marketUpdateRaw").textContent=md;const levels=Array.isArray(b.levels)?b.levels:[];$("marketMesLevels").innerHTML=levels.length?levels.map(l=>`<div class="market-level ${String(l.type||"").toLowerCase()}"><div><strong>${n(l.mes_low)}${Number(l.mes_high)!==Number(l.mes_low)?`–${n(l.mes_high)}`:""}</strong><span>${esc(l.type||"LEVEL")} · ${esc(l.status||"ACTIVE")}</span></div><small>${esc(l.label||"")}</small></div>`).join(""):'<div class="empty-state">No hourly MES levels stored.</div>';$("marketUpdateArchive").innerHTML=[...state.briefs].sort((a,b)=>new Date(b.brief_time)-new Date(a.brief_time)).map(x=>`<button class="market-archive-item ${x.id===b.id?"active":""}" data-brief-id="${esc(x.id)}"><strong>${dt(x.brief_time,true)}</strong><span>${esc(x.daily_bias||"—")}</span><small>${esc(x.headline||x.regime||"Hourly update")}</small></button>`).join("");}

function renderFootprint(){const f=state.footprints[0];setText("footprintTitle",f?`${f.contract} · ${f.row_count} prices`:"Bid × Ask Ladder");setText("footprintTime",f?dt(new Date(Number(f.bar_close_ms)).toISOString(),true):"—");const rows=Array.isArray(f?.ladder)?[...f.ladder].sort((a,b)=>Number(b.price)-Number(a.price)):[];$("footprintRows").innerHTML=rows.length?rows.map(r=>`<div class="footprint-row"><span>${n(r.price)}</span><span>${Number(r.bid_volume||0).toLocaleString()}</span><span>${Number(r.ask_volume||0).toLocaleString()}</span><span class="${Number(r.horizontal_delta)>=0?"pos":"neg"}">${Number(r.horizontal_delta)>=0?"+":""}${Number(r.horizontal_delta||0).toLocaleString()}</span></div>`).join(""):"<div class='muted'>No footprint cache rows.</div>";}
function ensureChart(){const el=$("priceChart");if(state.chart)return;if(!window.LightweightCharts){el.innerHTML="<div class='muted'>Chart library unavailable.</div>";return;}state.chart=LightweightCharts.createChart(el,{layout:{background:{color:"#0b111c"},textColor:"#9aacc0"},grid:{vertLines:{color:"#131e2d"},horzLines:{color:"#131e2d"}},rightPriceScale:{borderColor:"#233248"},timeScale:{borderColor:"#233248",timeVisible:true,secondsVisible:false},crosshair:{mode:0}});state.candles=state.chart.addSeries(LightweightCharts.CandlestickSeries,{upColor:"#44d19d",downColor:"#ff6b78",borderVisible:false,wickUpColor:"#44d19d",wickDownColor:"#ff6b78",priceLineVisible:true,lastValueVisible:true});new ResizeObserver(()=>state.chart?.applyOptions({width:el.clientWidth,height:el.clientHeight})).observe(el);}
function structuralImportantPenalty(r,ids){if(ids.has(r.level_id))return-100;const f=String(r.level_family||""),t=String(r.level_type||"");if(f==="PRICE_STRUCTURE")return 0;if(f==="PROFILE_DEVELOPING")return 1;if(f==="PROFILE_COMPLETED")return 2;if(f==="PROFILE_PERSISTENT")return 3;if(f==="PROFILE_COMPOSITE")return 4;if(f==="PROFILE_NODE")return 5;if(f==="PRICE_SWING"&&t.startsWith("SWING_1H_"))return 6;return 999;}
function structuralImportantLevels(px){const ids=new Set((state.models||[]).map(m=>m.level_id).filter(Boolean));return(state.levels||[]).map(r=>{const p=Number(r.reference_price),pen=structuralImportantPenalty(r,ids),d=Number.isFinite(px)&&Number.isFinite(p)?Math.abs(p-px):9999;return{r,pen,d,score:pen*4+Math.min(d,250)/10};}).filter(x=>x.pen<999).sort((a,b)=>a.score-b.score||a.d-b.d).slice(0,18).map(x=>x.r);}
window.FM_V33_IMPORTANT_LEVELS=structuralImportantLevels;
function renderChart(){ensureChart();if(!state.candles)return;const scale=state.chart.timeScale(),keepRange=renderChart.fitNext?null:scale.getVisibleLogicalRange();renderChart.fitNext=false;const data=state.bars.map(b=>({time:Math.floor(Number(b.bar_open_ms)/1000),open:Number(b.open),high:Number(b.high),low:Number(b.low),close:Number(b.close)})).filter(x=>[x.open,x.high,x.low,x.close].every(Number.isFinite));state.candles.setData(data);for(const l of state.priceLines){try{state.candles.removePriceLine(l);}catch{}}state.priceLines=[];const px=Number(latestBySymbol("ES")?.last),drawn=structuralImportantLevels(px);for(const r of drawn){const p=Number(r.reference_price);if(!Number.isFinite(p))continue;let color="#708196",style=2,width=1;const w=r.watch_probability,s=r.standard_probability,f=String(r.level_family||"");if(s!==null&&s!==undefined){color="#62c7ff";style=0;width=2;}else if(w!==null&&w!==undefined){color="#a98cff";style=0;width=2;}else if(f.startsWith("PROFILE_"))color="#f5bd59";else if(f==="PRICE_STRUCTURE")color="#d5dde8";try{state.priceLines.push(state.candles.createPriceLine({price:p,color,lineWidth:width,lineStyle:style,axisLabelVisible:true,title:String(r.level_type||"").replaceAll("_"," ")}));}catch{}}
  if(data.length){if(keepRange)try{scale.setVisibleLogicalRange(keepRange);}catch{}else scale.fitContent();}setText("chartStatus",`${state.tf} · ${data.length} completed display bars · ${drawn.length} important levels drawn (${state.levels.length} active loaded)`);}
function renderLevelTable(){const px=Number(latestBySymbol("ES")?.last),search=$("levelSearch").value.trim().toLowerCase(),fam=$("levelFamily").value;let rows=sortedLevels(px).filter(r=>(!fam||r.level_family===fam)&&(!search||`${r.level_type} ${r.level_family}`.toLowerCase().includes(search)));setText("levelLoaded",state.levels.length.toLocaleString());setText("levelNearest",rows[0]?n(rows[0].reference_price):"—");setText("watchAnnotated",state.levels.filter(x=>x.watch_probability!==null&&x.watch_probability!==undefined).length.toLocaleString());setText("standardAnnotated",state.levels.filter(x=>x.standard_probability!==null&&x.standard_probability!==undefined).length.toLocaleString());$("levelRows").innerHTML=rows.slice(0,500).map(r=>{const d=Number.isFinite(px)?Number(r.reference_price)-px:null;return `<tr><td>${d===null?"—":`${d>=0?"+":""}${n(d)}`}</td><td><strong>${n(r.reference_price)}</strong></td><td>${esc(r.level_type)}</td><td>${esc(r.level_family)}</td><td>${r.test_number??0}</td><td>${r.watch_probability===null||r.watch_probability===undefined?"—":pct(1-Number(r.watch_probability))}</td><td>${r.standard_probability===null||r.standard_probability===undefined?"—":pct(1-Number(r.standard_probability))}</td><td>${dt(r.available_at,true)}</td></tr>`}).join("");}
function renderFamilyOptions(){const sel=$("levelFamily"),cur=sel.value,fams=[...new Set(state.levels.map(x=>x.level_family).filter(Boolean))].sort();sel.innerHTML='<option value="">All families</option>'+fams.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");if(fams.includes(cur))sel.value=cur;}
function outcomeOf(e){const md=safeMeta(e.metadata);return md.outcome||md.resolution||md.resolved_outcome||"—";}
function renderEvents(){$("eventRows").innerHTML=state.events.slice(0,250).map(e=>`<tr><td>${dt(e.decision_time,true)}</td><td>${esc(e.role)}</td><td>${esc(e.state)}</td><td>${esc(e.level_type)}</td><td>${n(e.reference_price)}</td><td>${pct(e.rejection_probability)}</td><td>${pct(e.breakout_probability)}</td><td>${esc(outcomeOf(e))}</td></tr>`).join("");$("emaEventRows").innerHTML=state.emaEvents.slice(0,120).map(e=>`<tr><td>${dt(e.signal_close_utc,true)} · ${esc(e.signal)}</td><td>${esc(e.timeframe)}</td><td>${esc(e.direction)}</td><td class="${e.v2_decision==="TRADE"?"good-text":"muted"}">${esc(e.v2_decision)}</td><td>${esc(e.production_quality)}</td><td>${pct(e.v2_p_tp)}</td><td>${e.gam_predicted_ev===null?"—":Number(e.gam_predicted_ev).toFixed(3)+"R"}</td><td>${esc(e.execution_state)}</td><td>${esc(e.outcome||"—")}</td></tr>`).join("");}
function kv(rows){return rows.map(([a,b,cls])=>`<div class="kv-row"><span>${esc(a)}</span><span class="${cls||""}">${b}</span></div>`).join("");}
function renderAudit(){const feed=service("market_feed"),fp=service("market_footprint"),ema=service("ema_cci_v2_model"),oh=state.ofHealth;$("serviceHealth").innerHTML=kv([["Market feed",`${esc(feed?.status||"—")} · ${ageText(feed?.updated_at)}`],["Market footprint",`${esc(fp?.status||"—")} · ${ageText(fp?.updated_at)}`],["EMA/CCI",`${esc(ema?.status||"—")} · ${ageText(ema?.updated_at)}`],["Order Flow",`${esc(oh?.status||"—")} · ${ageText(oh?.updated_at)}`],["Serving gate",servingGate()?"LIVE":"PARKED",servingGate()?"good-text":"bad-text"]]);$("contractState").innerHTML=kv(state.contracts.map(c=>[`${c.symbol} ${c.contract_role}`,`${esc(c.contract)} · ${esc(c.feed_mode)} · tick ${c.tick_fresh?"fresh":"stale"} · ladder ${c.ladder_fresh?"fresh":"stale"} · scoring ${c.scoring_eligible?"yes":"no"}`]));$("modelIdentity").innerHTML=kv(state.models.map(m=>[m.role,`${esc(m.feature_version)} · model <span class="hash">${esc(shortHash(m.model_sha256))}</span> · cal <span class="hash">${esc(shortHash(m.calibrator_sha256))}</span>`]));const e=currentEma();$("emaIdentity").innerHTML=kv([["Feature version",esc(e?.feature_version||"—")],["GAM",`<span class="hash">${esc(e?.gam_sha256||"—")}</span>`],["V2",`<span class="hash">${esc(e?.v2_sha256||"—")}</span>`],["Inference",dt(e?.model_inference_at,true)]]);const meta=safeMeta(oh?.metadata);$("diagnostics").textContent=JSON.stringify({site_version:VERSION,last_fetch:state.lastFetch?.toISOString()||null,realtime:state.realtime,orderflow_gate:servingGate(),orderflow_health:{status:oh?.status||null,updated_at:oh?.updated_at||null,published_cutoff:meta.published_cutoff||null,publisher_version:meta.publisher_version||null,publisher_mode:meta.publisher_mode||null,website_serving_enabled:meta.website_serving_enabled??null,supabase_publication_enabled:meta.supabase_publication_enabled??null,production_scope:meta.production_scope||null},counts:{active_levels:state.levels.length,orderflow_events:state.events.length,ema_events:state.emaEvents.length,source_1m_bars:state.rawBars.length,display_bars:state.bars.length,footprints:state.footprints.length}},null,2);}
function renderAll(){renderSystem();renderQuotes();renderBrief();renderMarketUpdate();renderEma();renderOrderFlow();renderNearest();renderFootprint();renderFamilyOptions();renderLevelTable();renderEvents();renderAudit();renderChart();window.dispatchEvent(new CustomEvent("fm-v33-state-updated"));}
function scheduleFetch(){if(state.debounce)return;state.debounce=setTimeout(()=>{state.debounce=null;fetchAll(true);},1500);}
function scheduleRealtimeRender(table){if(!state.rtTables)state.rtTables=new Set();state.rtTables.add(table);if(state.renderDebounce)return;state.renderDebounce=setTimeout(()=>{const tables=[...state.rtTables];state.rtTables.clear();state.renderDebounce=null;renderAll();window.dispatchEvent(new CustomEvent("fm-v33-realtime-data",{detail:{tables}}));},250);}
function rtMerge(arr,row,keyFn,keepFn=null,sortFn=null,limit=null,remove=false){const key=keyFn(row);if(key===null||key===undefined||key==="")return arr;const prev=arr.find(x=>keyFn(x)===key)||null;let out=arr.filter(x=>keyFn(x)!==key);if(!remove){const merged={...(prev||{}),...row};if(!keepFn||keepFn(merged))out.push(merged);}if(sortFn)out.sort(sortFn);if(Number.isFinite(limit)&&limit>0&&out.length>limit)out=out.slice(0,limit);return out;}
const rtTimeDesc=field=>(a,b)=>new Date(b?.[field]||0)-new Date(a?.[field]||0);
const currentEsContract=()=>state.contracts.find(x=>x.symbol==="ES"&&x.contract_role==="CURRENT")?.contract||null;
function realtimeData(table,payload){try{const remove=String(payload?.eventType||"").toUpperCase()==="DELETE",row=remove?payload?.old:payload?.new;if(!row||typeof row!=="object")return;switch(table){
case "service_health":{const wanted=new Set(["market_feed","market_footprint","ema_cci_v2_model"]);if(!wanted.has(row.service))return;state.health=rtMerge(state.health,row,x=>x.service,x=>wanted.has(x.service),(a,b)=>String(a.service).localeCompare(String(b.service)),null,remove);break;}
case "ema_cci_v2_events":{if(!remove&&row.root!=="ES")return;state.emaEvents=rtMerge(state.emaEvents,row,x=>x.event_id,x=>x.root==="ES",rtTimeDesc("signal_close_utc"),120,remove);break;}
case "orderflow_service_health":{if(row.service!=="orderflow_fastpath")return;if(remove){if(state.ofHealth?.service===row.service)state.ofHealth=null;}else state.ofHealth={...(state.ofHealth||{}),...row};break;}
case "orderflow_model_state":{if(!remove&&row.root!=="ES")return;state.models=rtMerge(state.models,row,x=>`${x.root||""}|${x.role||""}`,x=>x.root==="ES",(a,b)=>String(a.role||"").localeCompare(String(b.role||"")),null,remove);break;}
case "orderflow_contract_state":{if(!remove&&!["ES","MES"].includes(row.symbol))return;const before=currentEsContract();state.contracts=rtMerge(state.contracts,row,x=>`${x.symbol||""}|${x.contract_role||""}`,x=>["ES","MES"].includes(x.symbol),(a,b)=>String(a.symbol||"").localeCompare(String(b.symbol||""))||String(a.contract_role||"").localeCompare(String(b.contract_role||"")),null,remove);const after=currentEsContract();if(before!==after){scheduleRealtimeRender(table);scheduleFetch();return;}break;}
case "orderflow_levels":{if(!remove&&row.root!=="ES")return;state.levels=rtMerge(state.levels,row,x=>x.level_id,x=>x.root==="ES"&&x.active===true,(a,b)=>Number(a.reference_price)-Number(b.reference_price)||String(a.level_id||"").localeCompare(String(b.level_id||"")),null,remove);break;}
case "orderflow_events":{if(!remove&&row.root!=="ES")return;state.events=rtMerge(state.events,row,x=>x.event_id,x=>x.root==="ES",rtTimeDesc("decision_time"),500,remove);break;}
case "orderflow_chart_bars":{const es=currentEsContract();if(!es)return;if(row.contract===undefined||row.timeframe===undefined||row.bar_open_ms===undefined){scheduleFetch();return;}if(row.contract!==es||row.timeframe!=="1m")return;state.rawBars=rtMerge(state.rawBars,row,x=>`${x.contract||""}|${x.timeframe||""}|${x.bar_open_ms}`,x=>x.contract===es&&x.timeframe==="1m",(a,b)=>Number(a.bar_open_ms)-Number(b.bar_open_ms),null,remove);if(state.rawBars.length>600)state.rawBars=state.rawBars.slice(-600);setDisplayBars();break;}
case "orderflow_footprint_cache":{if(row.contract===undefined||row.bar_open_ms===undefined){scheduleFetch();return;}state.footprints=rtMerge(state.footprints,row,x=>`${x.contract||""}|${x.bar_open_ms}`,null,(a,b)=>Number(b.bar_open_ms)-Number(a.bar_open_ms),12,remove);break;}
case "market_briefs":{state.briefs=rtMerge(state.briefs,row,x=>x.id,null,rtTimeDesc("brief_time"),8,remove);if(state.selectedBriefId&&!state.briefs.some(x=>String(x.id)===String(state.selectedBriefId)))state.selectedBriefId=state.briefs[0]?.id||null;break;}
default:scheduleFetch();return;}scheduleRealtimeRender(table);}catch(err){console.error("Realtime state apply failed",table,err);scheduleFetch();}}
function realtimeQuote(payload){const row=payload?.new;if(!row||!(["ES","MES"].includes(row.symbol)))return;state.quotes=state.quotes.filter(x=>x.symbol!==row.symbol);state.quotes.unshift(row);renderQuotes();renderSystem();window.dispatchEvent(new CustomEvent("fm-v33-live-quote",{detail:row}));window.dispatchEvent(new CustomEvent("fm-v33-state-updated"));}
function subscribe(){if(state.channel){client.removeChannel(state.channel);state.channel=null;}state.realtime="CONNECTING";const tables=["service_health","ema_cci_v2_events","orderflow_service_health","orderflow_model_state","orderflow_contract_state","orderflow_levels","orderflow_events","orderflow_chart_bars","orderflow_footprint_cache","market_briefs"];let ch=client.channel("v33-live").on("postgres_changes",{event:"*",schema:"public",table:"market_quotes_live"},realtimeQuote);for(const table of tables)ch=ch.on("postgres_changes",{event:"*",schema:"public",table},payload=>realtimeData(table,payload));state.channel=ch.subscribe(status=>{state.realtime=status;renderSystem();});}
async function show(session){state.session=session;$("authShell").classList.toggle("hidden",!!session);$("appShell").classList.toggle("hidden",!session);if(session){await fetchAll(true);subscribe();}else if(state.channel){client.removeChannel(state.channel);state.channel=null;}}
function wire(){document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".tab-panel").forEach(x=>x.classList.toggle("active",x.id===`tab-${b.dataset.tab}`));if(b.dataset.tab==="command")setTimeout(renderChart,30);if(b.dataset.tab==="market")renderMarketUpdate();}));document.querySelectorAll("[data-goto]").forEach(b=>b.addEventListener("click",()=>document.querySelector(`.tab[data-tab="${b.dataset.goto}"]`)?.click()));document.querySelectorAll("[data-tf]").forEach(b=>b.addEventListener("click",async()=>{state.tf=b.dataset.tf;renderChart.fitNext=true;document.querySelectorAll("[data-tf]").forEach(x=>x.classList.toggle("active",x===b));await fetchAll(true);}));$("refreshBtn").addEventListener("click",()=>fetchAll());$("signOutBtn").addEventListener("click",async()=>{await client.auth.signOut();});$("levelSearch").addEventListener("input",renderLevelTable);$("levelFamily").addEventListener("change",renderLevelTable);$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginError").textContent="";const {data,error}=await client.auth.signInWithPassword({email:$("loginEmail").value.trim(),password:$("loginPassword").value});if(error){$("loginError").textContent=error.message;return;}await show(data.session);});}
document.addEventListener("click",e=>{const b=e.target.closest("[data-brief-id]");if(b){state.selectedBriefId=b.dataset.briefId;renderMarketUpdate();}if(e.target.closest("#marketUpdateLatest")){state.selectedBriefId=latestBrief()?.id||null;renderMarketUpdate();}});
wire();setInterval(()=>{setText("clock",new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",weekday:"short",hour:"numeric",minute:"2-digit",second:"2-digit",hour12:true}).format(new Date())+" CT");renderSystem();},1000);setInterval(()=>{if(state.session)fetchAll(true);},POLL_MS);client.auth.getSession().then(({data})=>show(data.session));client.auth.onAuthStateChange((_event,session)=>{if(session!==state.session)show(session);});
})();