(()=>{"use strict";
const cfg=window.DASHBOARD_CONFIG_V35||{};
const $=id=>document.getElementById(id);
const TZ=cfg.timezone||"America/Chicago";
if(!cfg.supabaseUrl||!cfg.supabasePublishableKey){document.body.innerHTML='<div class="auth-shell"><div class="auth-card"><h1>V35 config missing</h1></div></div>';return;}
const client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const state={session:null,quote:null,health:[],nyBriefs:[],asiaBriefs:[],sessionView:"NY",briefSelected:{NY:null,ASIA:null},chartMode:"ohlc",ohlcTf:"1m",tickTf:"1000t",bars:[],chart:null,series:null,priceLines:[],livePriceLine:null,realtime:"CONNECTING",channel:null,trades:[],fetching:false,lastFetch:null};
window.FM_V35_CLIENT=client;window.FM_V35_STATE=state;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const num=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d}):"â€”";
const money=v=>Number.isFinite(Number(v))?`${Number(v)>=0?"+":"-"}$${Math.abs(Number(v)).toFixed(0)}`:"â€”";
const age=v=>{if(!v)return Infinity;const t=new Date(v).getTime();return Number.isFinite(t)?Math.max(0,(Date.now()-t)/1000):Infinity;};
const ageText=v=>{const s=age(v);if(!Number.isFinite(s))return"no timestamp";if(s<60)return`${Math.round(s)}s old`;if(s<3600)return`${Math.round(s/60)}m old`;return`${(s/3600).toFixed(1)}h old`;};
const dt=(v,withDate=false)=>{if(!v)return"â€”";try{return new Intl.DateTimeFormat("en-US",{timeZone:TZ,...(withDate?{month:"short",day:"numeric"}:{}),hour:"numeric",minute:"2-digit",hour12:true}).format(new Date(v))+" CT";}catch{return"â€”";}};
const toast=(m,bad=false)=>{const e=$("toast");if(!e)return;e.textContent=m;e.className=`toast${bad?" error":""}`;clearTimeout(toast._t);toast._t=setTimeout(()=>e.classList.add("hidden"),2800);};
const latest=(rows,key)=>[...(rows||[])].sort((a,b)=>new Date(b?.[key]||0)-new Date(a?.[key]||0))[0]||null;
async function q(label,p){const {data,error}=await p;if(error)throw new Error(`${label}: ${error.message}`);return data||[];}
function currentTf(){return state.chartMode==="ohlc"?state.ohlcTf:state.tickTf;}
function currentBriefs(){return state.sessionView==="NY"?state.nyBriefs:state.asiaBriefs;}
function selectedBrief(){const rows=currentBriefs(),id=state.briefSelected[state.sessionView];return rows.find(x=>String(x.id)===String(id))||latest(rows,"brief_time");}
function levelRange(l){const lo=Number(l.mnq_low??l.reference_low??l.price_low??l.mnq_level??l.price),hi=Number(l.mnq_high??l.mnq_low??l.reference_high??l.price_high??l.mnq_level??l.price);if(!Number.isFinite(lo))return null;const h=Number.isFinite(hi)?hi:lo;return{lo,hi:h,mid:(lo+h)/2};}
function levelKind(l){const s=`${l.type||""} ${l.label||""}`.toUpperCase();if(s.includes("RESIST"))return"resistance";if(s.includes("SUPPORT")||s.includes("RECLAIM"))return"support";return"pivot";}
function levelColor(l){return levelKind(l)==="resistance"?"#ff6b78":levelKind(l)==="support"?"#42d39b":"#f4bf63";}
function levelsForBrief(b){if(!b)return[];if(state.sessionView==="ASIA"&&Array.isArray(b.levels)&&b.levels.length)return b.levels;return Array.isArray(b.levels)?b.levels:[];}
function activeLevels(){return levelsForBrief(selectedBrief()).filter(x=>String(x.status||"ACTIVE").toUpperCase()!=="REMOVED"&&levelRange(x));}
function biasTone(v){const s=String(v||"").toUpperCase();return s.includes("BULL")?"good":s.includes("BEAR")?"bad":"neutral";}
function markdown(src){let s=esc(src||"");s=s.replace(/^### (.+)$/gm,"<h3>$1</h3>").replace(/^## (.+)$/gm,"<h2>$1</h2>").replace(/^# (.+)$/gm,"<h1>$1</h1>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>");const lines=s.split("\n");let out=[],inList=false;for(const line of lines){if(/^\s*[-*] /.test(line)){if(!inList){out.push("<ul>");inList=true;}out.push(`<li>${line.replace(/^\s*[-*] /,"")}</li>`);}else{if(inList){out.push("</ul>");inList=false;}if(/^<h[123]>/.test(line))out.push(line);else if(line.trim())out.push(`<p>${line}</p>`);}}if(inList)out.push("</ul>");return out.join("");}
function defaultSession(){const h=Number(new Intl.DateTimeFormat("en-US",{timeZone:TZ,hour:"2-digit",hourCycle:"h23"}).format(new Date()));return h>=8&&h<16?"NY":"ASIA";}
try{state.sessionView=localStorage.getItem("v35-session")||defaultSession();state.chartMode=localStorage.getItem("v35-chart-mode")||"ohlc";state.ohlcTf=localStorage.getItem("v35-ohlc-tf")||"1m";state.tickTf=localStorage.getItem("v35-tick-tf")||"1000t";}catch{state.sessionView=defaultSession();}

function syncSessionUi(){document.querySelectorAll("[data-session]").forEach(b=>b.classList.toggle("active",b.dataset.session===state.sessionView));$("sessionLabel").textContent=state.sessionView==="NY"?"NY SESSION":"ASIA / GLOBEX";}
function setSession(v){if(!["NY","ASIA"].includes(v))return;state.sessionView=v;try{localStorage.setItem("v35-session",v);}catch{}syncSessionUi();renderBrief();renderLevels();renderMarketBrief();renderChartLevels();}
function syncChartUi(){document.querySelectorAll("#chartModeToggle [data-mode]").forEach(b=>b.classList.toggle("active",b.dataset.mode===state.chartMode));$("ohlcTf").classList.toggle("hidden",state.chartMode!=="ohlc");$("tickTf").classList.toggle("hidden",state.chartMode!=="tick");$("ohlcTf").value=state.ohlcTf;$("tickTf").value=state.tickTf;const tf=currentTf();$("chartTitle").textContent=state.chartMode==="ohlc"?`OHLC Â· ${tf==="1m"?"1 minute":"5 minutes"}`:`Tick chart Â· ${tf.replace("t","")} ticks`;}
function setChartMode(v){state.chartMode=v;try{localStorage.setItem("v35-chart-mode",v);}catch{}syncChartUi();fetchBars(true);}

function initChart(){if(state.chart)return;const L=window.LightweightCharts;state.chart=L.createChart($("marketChart"),{autoSize:true,layout:{background:{type:"solid",color:"#07111a"},textColor:"#8299ae",fontFamily:"Inter,system-ui,sans-serif"},grid:{vertLines:{color:"#102030"},horzLines:{color:"#102030"}},rightPriceScale:{borderColor:"#253b50",scaleMargins:{top:.08,bottom:.08}},timeScale:{borderColor:"#253b50",timeVisible:true,secondsVisible:false,tickMarkFormatter:t=>{try{return new Intl.DateTimeFormat("en-US",{timeZone:TZ,hour:"numeric",minute:"2-digit",hour12:true}).format(new Date(Number(t)*1000));}catch{return null;}}},crosshair:{vertLine:{color:"#38536c",labelBackgroundColor:"#21384e"},horzLine:{color:"#38536c",labelBackgroundColor:"#21384e"}},localization:{priceFormatter:p=>Number(p).toFixed(2)}});state.series=state.chart.addSeries(L.CandlestickSeries,{upColor:"#42d39b",downColor:"#ff6b78",wickUpColor:"#42d39b",wickDownColor:"#ff6b78",borderVisible:false,priceLineVisible:false,lastValueVisible:false});}
function renderBars(fit=false){initChart();let prevTime=-Infinity;const data=state.bars.map(x=>{let time=state.chartMode==="tick"?Number(x.bar_close_ms)/1000:Math.floor(Number(x.bar_open_ms)/1000);if(state.chartMode==="tick"&&time<=prevTime)time=prevTime+0.001;prevTime=time;return{time,open:x.open,high:x.high,low:x.low,close:x.close};});state.series.setData(data);renderLivePriceLine();$("barCount").textContent=`${data.length.toLocaleString()} bars`;const last=state.bars[state.bars.length-1];$("chartStatus").textContent=last?`${currentTf()} Â· last completed ${dt(last.bar_close_ms,true)} Â· ${ageText(last.bar_close_ms)}`:`No MNQ ${currentTf()} bars received yet.`;if(fit&&data.length)state.chart.timeScale().fitContent();renderChartLevels();renderSystem();}
function renderChartLevels(){if(!state.series)return;for(const p of state.priceLines){try{state.series.removePriceLine(p);}catch{}}state.priceLines=[];for(const l of activeLevels().slice(0,18)){const r=levelRange(l);if(!r)continue;try{state.priceLines.push(state.series.createPriceLine({price:r.mid,color:levelColor(l),lineWidth:1,lineStyle:2,axisLabelVisible:true,title:String(l.label||l.type||"Level").slice(0,22)}));}catch{}}}


function renderLivePriceLine(){
  if(!state.series)return;
  const px=Number(state.quote?.last);
  if(!Number.isFinite(px)){
    if(state.livePriceLine){try{state.series.removePriceLine(state.livePriceLine);}catch{}state.livePriceLine=null;}
    return;
  }
  const opts={price:px,color:"#4db6ff",lineWidth:1,lineStyle:0,axisLabelVisible:true,title:""};
  if(!state.livePriceLine){
    try{state.livePriceLine=state.series.createPriceLine(opts);}catch{}
  }else{
    try{state.livePriceLine.applyOptions(opts);}catch{}
  }
}

function renderQuote(){const x=state.quote,stale=!x||age(x.updated_at||x.timestamp)>(cfg.quoteMaxAgeSeconds||120);$("feedPill").textContent=stale?"FEED STALE":"MNQ LIVE";$("feedPill").className=`status-pill ${stale?"degraded":"live"}`;$("mnqHeader").textContent=x?`MNQ ${num(x.last)}`:"MNQ â€”";$("livePrice").textContent=x?num(x.last):"â€”";$("bidPrice").textContent=x?num(x.bid):"â€”";$("askPrice").textContent=x?num(x.ask):"â€”";const sp=x&&Number.isFinite(Number(x.ask))&&Number.isFinite(Number(x.bid))?Number(x.ask)-Number(x.bid):null;$("spreadText").textContent=sp===null?"â€”":`${sp.toFixed(2)} pts`;$("contractText").textContent=x?.contract||"â€”";$("quoteAge").textContent=x?ageText(x.updated_at||x.timestamp):"â€”";$("quoteAge").className=`state-pill ${stale?"bad":"good"}`;renderLivePriceLine();renderJournalOpen();}
function renderBrief(){const b=selectedBrief();if(!b){$("biasText").textContent="Waiting for MNQ brief";$("regimePill").textContent="â€”";$("headlineText").textContent="The next valid scheduled MNQ market update will populate this session.";$("briefTime").textContent="â€”";$("briefSource").textContent="MNQ native";$("bullText").textContent="â€”";$("bearText").textContent="â€”";$("summaryText").textContent="â€”";$("biasCard").className="panel bias-card neutral";return;}const tone=biasTone(b.daily_bias);$("biasCard").className=`panel bias-card ${tone}`;$("biasText").textContent=b.daily_bias||"NEUTRAL";$("regimePill").textContent=b.regime||b.session_phase||"â€”";$("regimePill").className=`state-pill ${tone}`;$("headlineText").textContent=b.headline||b.summary||"â€”";$("briefTime").textContent=dt(b.brief_time,true);$("briefSource").textContent=`${state.sessionView} Â· MNQ native`;$("bullText").textContent=b.bullish_scenario||"â€”";$("bearText").textContent=b.bearish_scenario||"â€”";$("summaryText").textContent=b.summary||"â€”";}
function renderLevels(){const rows=activeLevels(),px=Number(state.quote?.last);$("levelCount").textContent=String(rows.length);const h=$("levelsList");if(!rows.length){h.innerHTML='<div class="empty-state">No MNQ-native levels stored yet for this session.</div>';return;}h.innerHTML=rows.map(l=>{const r=levelRange(l),k=levelKind(l),dist=Number.isFinite(px)?r.mid-px:null,price=r.lo===r.hi?num(r.lo):`${num(r.lo)}â€“${num(r.hi)}`;return`<div class="level-row ${k}"><div class="level-main"><strong>${esc(l.label||l.type||"MNQ level")}</strong><small>${esc(String(l.status||"ACTIVE").toUpperCase())} Â· ${esc(l.importance||"standard")} Â· ${esc(l.source_anchor||l.source_session||state.sessionView)}</small></div><div class="level-price"><strong>${price}</strong><small>${dist===null?"":`${dist>=0?"+":""}${dist.toFixed(2)} pts`}</small></div></div>`;}).join("");renderChartLevels();}
function renderMarketBrief(){const rows=currentBriefs(),b=selectedBrief();const sel=$("briefArchive");sel.innerHTML=rows.length?rows.map(x=>`<option value="${esc(x.id)}" ${b&&String(x.id)===String(b.id)?"selected":""}>${esc(dt(x.brief_time,true))} Â· ${esc(x.daily_bias||"NEUTRAL")}</option>`).join(""):'<option>No MNQ briefs</option>';if(!b){$("briefMarketSource").textContent=`${state.sessionView} Â· MNQ`;$("briefTitle").textContent="Waiting for MNQ brief";$("briefArchiveTime").textContent="â€”";$("briefBody").innerHTML='<div class="empty-state">No MNQ-native brief has been stored for this session yet.</div>';return;}$("briefMarketSource").textContent=`${state.sessionView} Â· MNQ`;$("briefTitle").textContent=b.headline||`${b.daily_bias||"NEUTRAL"} MNQ`;$("briefArchiveTime").textContent=dt(b.brief_time,true);$("briefBody").innerHTML=markdown(b.full_markdown||b.summary||b.headline||"");}
function openTradeRow(){return state.trades.find(x=>x.status==="OPEN")||null;}
function tradePnl(t){if(!t||!state.quote)return null;const px=Number(state.quote.last),entry=Number(t.avg_entry_price),qty=Number(t.open_contracts||0),side=t.direction==="LONG"?1:-1;if(![px,entry,qty].every(Number.isFinite))return null;return Number(t.realized_pnl_dollars||0)+side*(px-entry)*qty*2;}
function renderJournal(){const body=$("tradeLedger");body.innerHTML=state.trades.length?state.trades.map(t=>`<tr><td>${esc(dt(t.opened_at,true))}</td><td>${esc(t.direction)}</td><td>${esc(t.status)}</td><td>${num(t.avg_entry_price)}</td><td>${num(t.avg_exit_price)}</td><td>${esc(t.open_contracts??0)} / ${esc(t.initial_contracts??0)}</td><td class="${Number(t.realized_pnl_dollars)>=0?"positive":"negative"}">${money(t.realized_pnl_dollars)}</td></tr>`).join(""):'<tr><td colspan="7">No MNQ trades.</td></tr>';renderJournalOpen();}
function renderJournalOpen(){const t=openTradeRow(),box=$("openTradeBody");if(!t){$("openTradeTitle").textContent="No open MNQ trade";$("openPnl").textContent="â€”";box.className="empty-state";box.innerHTML="Open a journal trade to track live P/L.";return;}const pnl=tradePnl(t);$("openTradeTitle").textContent=`MNQ ${t.direction} Â· ${t.open_contracts} open`;$("openPnl").textContent=money(pnl);$("openPnl").className=Number(pnl)>=0?"positive":"negative";box.className="";box.innerHTML=`<div class="trade-detail"><span>Avg entry / live</span><strong>${num(t.avg_entry_price)} / ${num(state.quote?.last)}</strong></div><div class="trade-detail"><span>Current stop</span><strong>${num(t.current_stop_price)}</strong></div><div class="form-actions" style="margin-top:12px"><button class="ghost" data-trade-action="SCALE_IN">Scale in</button><button class="ghost" data-trade-action="TRIM">Trim</button><button class="ghost" data-trade-action="STOP_UPDATE">Move stop</button><button class="ghost" data-trade-action="EXIT">Exit</button></div>`;}
function renderSystem(){const feed=(state.health||[]).find(x=>x.service==="market_feed"),lastBar=state.bars[state.bars.length-1],b=selectedBrief();const items=[
["Market feed",feed?.status||"UNKNOWN",feed?.updated_at?ageText(feed.updated_at):"No health timestamp"],
["MNQ quote",state.quote?num(state.quote.last):"MISSING",state.quote?`${state.quote.contract||""} Â· ${ageText(state.quote.updated_at||state.quote.timestamp)}`:"No MNQ quote"],
[`${currentTf()} bars`,state.bars.length?`${state.bars.length} loaded`:"WAITING",lastBar?ageText(lastBar.received_at||lastBar.bar_close_ms):"No completed bars"],
["Realtime",state.realtime,state.channel?"quote + bar subscriptions":"subscription not connected"],
[`${state.sessionView} brief`,b?b.daily_bias||"READY":"WAITING",b?ageText(b.brief_time):"No MNQ-native brief"]];$("systemGrid").innerHTML=items.map(([a,b,c])=>`<div class="system-card"><div class="eyebrow">${esc(a)}</div><strong>${esc(b)}</strong><small>${esc(c)}</small></div>`).join("");}
function renderAll(){renderQuote();renderBrief();renderLevels();renderMarketBrief();renderJournal();renderSystem();syncSessionUi();syncChartUi();}

async function fetchBars(fit=false){if(!state.session)return;const tf=currentTf(),limit=state.chartMode==="ohlc"?700:500;try{let req=client.from("market_bars_live").select("contract,timeframe,bar_open_ms,bar_close_ms,payload,received_at").eq("data_type","ohlcv").eq("symbol","MNQ").eq("timeframe",tf).lte("bar_close_ms",Date.now()).order("bar_open_ms",{ascending:false}).limit(limit);if(state.quote?.contract)req=req.eq("contract",state.quote.contract);const rows=await q(`MNQ ${tf} bars`,req);state.bars=[...rows].reverse().map(x=>{const p=x.payload&&typeof x.payload==="object"?x.payload:{};return{...x,bar_open_ms:Number(x.bar_open_ms),bar_close_ms:Number(x.bar_close_ms),open:Number(p.open),high:Number(p.high),low:Number(p.low),close:Number(p.close),volume:Number(p.volume||0)};}).filter(x=>[x.bar_open_ms,x.bar_close_ms,x.open,x.high,x.low,x.close].every(Number.isFinite));renderBars(fit);}catch(e){console.error(e);state.bars=[];renderBars(false);toast(e.message,true);}}
async function fetchCore(silent=false){if(!state.session||state.fetching)return;state.fetching=true;try{const [quotes,health,ny,asia,trades]=await Promise.all([
q("MNQ quote",client.from("market_quotes_live").select("symbol,contract,bid,ask,last,bid_size,ask_size,last_size,session_volume,timestamp,source,updated_at").eq("symbol","MNQ").order("updated_at",{ascending:false}).limit(1)),
q("market feed health",client.from("service_health").select("service,status,message,last_event_at,updated_at,metadata").eq("service","market_feed")),
q("NY MNQ briefs",client.from("market_briefs").select("id,brief_time,session_date,instrument,reference_price,reference_time,session_phase,daily_bias,prior_bias,bias_changed,regime,headline,summary,bullish_scenario,bearish_scenario,levels,full_markdown,published_by,created_at,updated_at").eq("instrument","MNQ").order("brief_time",{ascending:false}).limit(10)),
q("Asia MNQ briefs",client.from("market_briefs_asia").select("id,brief_time,session_date,instrument,reference_price,reference_time,session_phase,daily_bias,prior_bias,bias_changed,regime,headline,summary,bullish_scenario,bearish_scenario,ny_carry_levels,asia_levels,levels,full_markdown,published_by,created_at,updated_at").eq("instrument","MNQ").order("brief_time",{ascending:false}).limit(10)),
q("MNQ trades",client.from("trades").select("*").eq("instrument","MNQ").order("opened_at",{ascending:false}).limit(100))]);
state.quote=quotes[0]||null;state.health=health;state.nyBriefs=ny;state.asiaBriefs=asia;state.trades=trades;state.lastFetch=new Date();renderAll();await fetchBars(false);if(!silent)toast("MNQ dashboard refreshed");}catch(e){console.error(e);toast(e.message,true);renderSystem();}finally{state.fetching=false;}}
let barDebounce=null;
function subscribeRealtime(){if(state.channel){try{client.removeChannel(state.channel);}catch{}}state.realtime="CONNECTING";state.channel=client.channel("v35-mnq-live")
.on("postgres_changes",{event:"*",schema:"public",table:"market_quotes_live",filter:"symbol=eq.MNQ"},payload=>{state.quote=payload.new||state.quote;renderQuote();renderLevels();renderSystem();})
.on("postgres_changes",{event:"*",schema:"public",table:"market_bars_live",filter:"symbol=eq.MNQ"},payload=>{if(payload.new?.timeframe!==currentTf())return;clearTimeout(barDebounce);barDebounce=setTimeout(()=>fetchBars(false),350);})
.on("postgres_changes",{event:"INSERT",schema:"public",table:"market_briefs"},payload=>{if(payload.new?.instrument==="MNQ")fetchCore(true);})
.subscribe(status=>{state.realtime=status;renderSystem();});}
async function rpc(name,args){const {data,error}=await client.rpc(name,args);if(error)throw error;return data;}
async function startTrade(e){e.preventDefault();$("tradeError").textContent="";try{const side=$("tradeSide").value,qty=Number($("tradeQty").value),entry=Number($("tradeEntry").value),stop=Number($("tradeStop").value);await rpc("start_trade",{p_instrument:"MNQ",p_direction:side,p_entry_price:entry,p_stop_price:stop,p_contracts:qty,p_market_snapshot_id:null,p_entry_context:{source:"V35_MNQ_JOURNAL",mnq_price:Number(state.quote?.last)||null,chart_timeframe:currentTf(),session:state.sessionView},p_notes:"V35 manual MNQ journal",p_event_time:new Date().toISOString()});await fetchCore(true);toast("MNQ journal trade opened");}catch(err){$("tradeError").textContent=err.message||String(err);}}
async function tradeAction(type){const t=openTradeRow();if(!t)return;try{if(type==="STOP_UPDATE"){const v=Number(prompt("New MNQ stop",t.current_stop_price));if(!Number.isFinite(v))return;await rpc("add_trade_event",{p_trade_id:t.id,p_event_type:"STOP_UPDATE",p_quantity:null,p_price:null,p_stop_price:v,p_reason:"MANUAL",p_notes:"V35 stop update",p_market_snapshot_id:null,p_context:{source:"V35_MNQ_JOURNAL"},p_event_time:new Date().toISOString()});}
else{const live=Number(state.quote?.last),price=Number(prompt(`${type.replace("_"," ")} fill price`,Number.isFinite(live)?live:t.avg_entry_price));if(!Number.isFinite(price))return;let qty=null;if(type!=="EXIT"){qty=Number(prompt("Contracts",1));if(!Number.isInteger(qty)||qty<=0)return;}await rpc("add_trade_event",{p_trade_id:t.id,p_event_type:type,p_quantity:qty,p_price:price,p_stop_price:null,p_reason:"MANUAL",p_notes:`V35 ${type}`,p_market_snapshot_id:null,p_context:{source:"V35_MNQ_JOURNAL"},p_event_time:new Date().toISOString()});}await fetchCore(true);toast(`Trade ${type.toLowerCase().replace("_"," ")} saved`);}catch(err){toast(err.message||String(err),true);}}
function bind(){document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".tab-panel").forEach(x=>x.classList.toggle("active",x.id===`tab-${b.dataset.tab}`));if(b.dataset.tab==="desk"&&state.chart)setTimeout(()=>state.chart.timeScale().fitContent(),50);}));
document.querySelectorAll("[data-session]").forEach(b=>b.addEventListener("click",()=>setSession(b.dataset.session)));
document.querySelectorAll("#chartModeToggle [data-mode]").forEach(b=>b.addEventListener("click",()=>setChartMode(b.dataset.mode)));
$("ohlcTf").addEventListener("change",e=>{state.ohlcTf=e.target.value;try{localStorage.setItem("v35-ohlc-tf",state.ohlcTf);}catch{}syncChartUi();fetchBars(true);});
$("tickTf").addEventListener("change",e=>{state.tickTf=e.target.value;try{localStorage.setItem("v35-tick-tf",state.tickTf);}catch{}syncChartUi();fetchBars(true);});
$("fitChartBtn").addEventListener("click",()=>state.chart?.timeScale().fitContent());$("refreshBtn").addEventListener("click",()=>fetchCore(false));$("journalRefresh").addEventListener("click",()=>fetchCore(true));$("briefArchive").addEventListener("change",e=>{state.briefSelected[state.sessionView]=e.target.value;renderBrief();renderLevels();renderMarketBrief();});
$("useLiveEntry").addEventListener("click",()=>{if(state.quote?.last)$("tradeEntry").value=Number(state.quote.last).toFixed(2);});$("newTradeForm").addEventListener("submit",startTrade);$("openTradeBody").addEventListener("click",e=>{const b=e.target.closest("[data-trade-action]");if(b)tradeAction(b.dataset.tradeAction);});
$("signOutBtn").addEventListener("click",async()=>{await client.auth.signOut();location.reload();});
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginError").textContent="";const {error}=await client.auth.signInWithPassword({email:$("loginEmail").value,password:$("loginPassword").value});if(error)$("loginError").textContent=error.message;});}
function clock(){try{$("clock").textContent=new Intl.DateTimeFormat("en-US",{timeZone:TZ,weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit",second:"2-digit",hour12:true}).format(new Date())+" CT";}catch{}}
async function boot(session){state.session=session;$("authShell").classList.add("hidden");$("appShell").classList.remove("hidden");syncSessionUi();syncChartUi();initChart();subscribeRealtime();await fetchCore(true);clock();setInterval(clock,1000);setInterval(()=>fetchCore(true),Math.max(15,Number(cfg.safetyPollSeconds||30))*1000);}
bind();client.auth.onAuthStateChange((_event,session)=>{if(session&&!state.session)boot(session);else if(!session){state.session=null;$("appShell").classList.add("hidden");$("authShell").classList.remove("hidden");}});client.auth.getSession().then(({data})=>{if(data.session)boot(data.session);});
})();

