(()=>{"use strict";
const $=id=>document.getElementById(id);
let trades=[],events=[],selected=null;
const client=()=>window.FM_V33_CLIENT,state=()=>window.FM_V33_STATE;
const fmt=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toFixed(d):"—";
const money=v=>Number.isFinite(Number(v))?`${Number(v)>0?"+":Number(v)<0?"-":""}$${Math.abs(Number(v)).toFixed(0)}`:"—";
const ct=v=>{try{return new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v))+" CT";}catch{return"—";}};
function mesQuote(){return (state()?.quotes||[]).filter(x=>x.symbol==="MES").sort((a,b)=>new Date(b.updated_at||b.timestamp)-new Date(a.updated_at||a.timestamp))[0]||{};}
function live(){return Number(mesQuote().last);}
function pnl(r){const p=live(),e=Number(r.avg_entry_price),q=Number(r.open_contracts),s=r.direction==="LONG"?1:-1;return[p,e,q].every(Number.isFinite)?s*(p-e)*q*5:null;}
function target(r){const e=events.filter(x=>x.trade_id===r.id).sort((a,b)=>new Date(b.event_time)-new Date(a.event_time)).find(x=>String(x.notes||"").startsWith("TARGET_UPDATE|"));const p=e?Number(String(e.notes).split("|")[1]):NaN;return Number.isFinite(p)?p:null;}
async function rpc(name,args){const {data,error}=await client().rpc(name,args);if(error)throw error;return data;}
async function fetchData(){if(!client())return;const [tr,ev]=await Promise.all([client().from("trades").select("*").eq("instrument","MES").order("opened_at",{ascending:false}).limit(150),client().from("trade_events").select("*").order("event_time",{ascending:false}).limit(1500)]);if(tr.error)throw tr.error;if(ev.error)throw ev.error;trades=tr.data||[];events=(ev.data||[]).filter(x=>trades.some(t=>t.id===x.trade_id));if(!selected&&trades.length)selected=trades.find(x=>x.status==="OPEN")?.id||trades[0].id;}
function modelPlan(){return(state()?.emaEvents||[]).find(x=>x.root==="ES"&&x.v2_decision==="TRADE"&&["WAIT_NEXT_BAR","WAIT_ENTRY","WORKING","OPEN","FILLED","ENTRY_PENDING"].includes(String(x.execution_state||"").toUpperCase()))||null;}
async function writeTarget(id,t){if(Number.isFinite(t))await rpc("add_trade_event",{p_trade_id:id,p_event_type:"NOTE",p_quantity:null,p_price:null,p_stop_price:null,p_reason:"MANUAL",p_notes:`TARGET_UPDATE|${t}`,p_market_snapshot_id:null,p_context:{target_price:t,source:"V33_MES_JOURNAL"}});}
function mount(){const m=$("journalMount");if(!m)return;const p=modelPlan();m.innerHTML=`${p?`<article class="panel model-plan-banner"><div class="panel-head"><div><div class="eyebrow">CURRENT FROZEN EMA/CCI PLAN</div><h3>${p.timeframe} ${p.direction} · ${p.production_quality||"—"} · P(TP) ${Number(p.v2_p_tp*100).toFixed(1)}%</h3></div><button id="journalUseModelPlan" class="text-button">Use model plan</button></div><div>Entry ${p.entry_method==="NEXT_BAR_MARKET"?"MARKET":fmt(p.planned_entry_price)} · SL ${fmt(p.actual_stop_price??p.planned_stop_price)} · TP ${fmt(p.actual_target_price??p.planned_target_price)}</div></article>`:""}
<article class="panel"><div class="panel-head"><div><div class="eyebrow">NEW MES TRADE</div><h3>Manual fill record</h3></div><small>Live MES ${fmt(live())}</small></div><form id="journalNewTrade" class="journal-form"><label>Side<select id="journalDirection"><option>LONG</option><option>SHORT</option></select></label><label>Contracts<input id="journalContracts" type="number" min="1" value="1"></label><label>Entry<input id="journalEntry" type="number" step="0.25"></label><label>Stop<input id="journalStop" type="number" step="0.25"></label><label>Target<input id="journalTarget" type="number" step="0.25"></label><button id="journalUseLive" type="button" class="text-button">Use live MES</button><button type="submit" class="primary">Open journal trade</button></form><div id="journalError" class="error"></div></article>
<article class="panel"><div class="panel-head"><h3>MES Trades</h3><small>${trades.filter(x=>x.status==="OPEN").length} open</small></div><div class="table-wrap"><table><thead><tr><th>Opened</th><th>Side</th><th>Status</th><th>Entry</th><th>Live</th><th>Open P/L</th><th>Realized</th><th>Qty</th><th>Stop</th><th>TP</th></tr></thead><tbody>${trades.map(r=>`<tr data-journal-id="${r.id}" class="${r.id===selected?"selected":""}"><td>${ct(r.opened_at)}</td><td>${r.direction}</td><td>${r.status}</td><td>${fmt(r.avg_entry_price)}</td><td>${r.status==="OPEN"?fmt(live()):"—"}</td><td>${r.status==="OPEN"?money(pnl(r)):"—"}</td><td>${money(r.realized_pnl_dollars)}</td><td>${r.open_contracts}</td><td>${fmt(r.current_stop_price)}</td><td>${fmt(target(r))}</td></tr>`).join("")||'<tr><td colspan="10">No MES journal trades.</td></tr>'}</tbody></table></div></article><div id="journalDetail"></div>`;renderDetail();}
function renderDetail(){const h=$("journalDetail"),r=trades.find(x=>x.id===selected);if(!h||!r){if(h)h.innerHTML="";return;}const tp=target(r),open=r.status==="OPEN";h.innerHTML=`<article class="panel"><div class="panel-head"><div><div class="eyebrow">SELECTED TRADE</div><h3>MES ${r.direction} · ${r.status}</h3></div><strong>${open?money(pnl(r)):money(r.realized_pnl_dollars)}</strong></div><div class="journal-summary"><div><span>Entry</span><strong>${fmt(r.avg_entry_price)}</strong></div><div><span>Live</span><strong>${open?fmt(live()):"—"}</strong></div><div><span>Qty</span><strong>${r.open_contracts}</strong></div><div><span>Stop</span><strong>${fmt(r.current_stop_price)}</strong></div><div><span>Target</span><strong>${fmt(tp)}</strong></div></div>${open?`<div class="journal-manage"><form id="journalAction"><label>Action<select id="journalActionType"><option value="SCALE_IN">Scale In</option><option value="TRIM">Trim</option><option value="TAKE_PROFIT">Take Profit</option><option value="EXIT">Exit Remaining</option></select></label><label>Qty<input id="journalActionQty" type="number" min="1" value="1"></label><label>Fill<input id="journalActionPrice" type="number" step="0.25" value="${fmt(live())}"></label><button type="submit">Save action</button></form><form id="journalStopForm"><label>New Stop<input id="journalNewStop" type="number" step="0.25" value="${fmt(r.current_stop_price)}"></label><button type="submit">Save stop</button></form><form id="journalTargetForm"><label>New Target<input id="journalNewTarget" type="number" step="0.25" value="${tp==null?"":fmt(tp)}"></label><button type="submit">Save target</button></form></div>`:""}</article>`;}
async function refresh(){try{await fetchData();mount();}catch(e){console.warn(e);const n=$("journalError");if(n)n.textContent=e.message||String(e);}}
async function openTrade(){const d=$("journalDirection").value,q=Number($("journalContracts").value),e=Number($("journalEntry").value),s=Number($("journalStop").value),t=Number($("journalTarget").value),err=$("journalError");err.textContent="";if(!Number.isInteger(q)||q<=0||![e,s].every(Number.isFinite)){err.textContent="Enter valid MES trade details.";return;}if(d==="LONG"?s>=e:s<=e){err.textContent="Stop is on the wrong side of entry.";return;}const plan=modelPlan();await rpc("start_trade",{p_instrument:"MES",p_direction:d,p_entry_price:e,p_stop_price:s,p_contracts:q,p_market_snapshot_id:null,p_entry_context:{source:"V33_MES_JOURNAL",model_event_id:plan?.event_id||null,recorded_at:new Date().toISOString()},p_notes:null});await fetchData();const n=trades.filter(x=>x.status==="OPEN").sort((a,b)=>new Date(b.opened_at)-new Date(a.opened_at))[0];if(n&&Number.isFinite(t))await writeTarget(n.id,t);selected=n?.id||selected;await refresh();}
async function action(){const r=trades.find(x=>x.id===selected);if(!r)return;const type=$("journalActionType").value,q=Number($("journalActionQty").value),p=Number($("journalActionPrice").value);let eventType=type,reason="MANUAL",qty=q;if(type==="TAKE_PROFIT"){eventType=q>=Number(r.open_contracts)?"EXIT":"TRIM";reason="PRIMARY_TARGET";qty=eventType==="EXIT"?null:q;}else if(type==="EXIT")qty=null;await rpc("add_trade_event",{p_trade_id:r.id,p_event_type:eventType,p_quantity:qty,p_price:p,p_stop_price:null,p_reason:reason,p_notes:null,p_market_snapshot_id:null,p_context:{source:"V33_MES_JOURNAL"}});await refresh();}
async function saveStop(){const r=trades.find(x=>x.id===selected),p=Number($("journalNewStop").value);await rpc("add_trade_event",{p_trade_id:r.id,p_event_type:"STOP_UPDATE",p_quantity:null,p_price:null,p_stop_price:p,p_reason:"STRUCTURE_UPDATE",p_notes:null,p_market_snapshot_id:null,p_context:{source:"V33_MES_JOURNAL"}});await refresh();}
async function saveTarget(){const r=trades.find(x=>x.id===selected),p=Number($("journalNewTarget").value);await writeTarget(r.id,p);await refresh();}
document.addEventListener("click",e=>{if(e.target.closest('[data-tab="journal"]')||e.target.closest("#journalRefresh"))setTimeout(refresh,0);const row=e.target.closest("[data-journal-id]");if(row){selected=row.dataset.journalId;renderDetail();}if(e.target.closest("#journalUseLive")){const p=live();if(Number.isFinite(p))$("journalEntry").value=p.toFixed(2);}if(e.target.closest("#journalUseModelPlan")){const p=modelPlan();if(!p)return;$("journalDirection").value=p.direction;const fill=Number(p.actual_fill_price??p.planned_entry_price),stop=Number(p.actual_stop_price??p.planned_stop_price),target=Number(p.actual_target_price??p.planned_target_price);if(Number.isFinite(fill))$("journalEntry").value=fill.toFixed(2);if(Number.isFinite(stop))$("journalStop").value=stop.toFixed(2);if(Number.isFinite(target))$("journalTarget").value=target.toFixed(2);}});
document.addEventListener("submit",e=>{if(e.target.id==="journalNewTrade"){e.preventDefault();openTrade().catch(x=>$("journalError").textContent=x.message||String(x));}if(e.target.id==="journalAction"){e.preventDefault();action().catch(console.warn);}if(e.target.id==="journalStopForm"){e.preventDefault();saveStop().catch(console.warn);}if(e.target.id==="journalTargetForm"){e.preventDefault();saveTarget().catch(console.warn);}},true);
window.addEventListener("fm-v33-state-updated",()=>{if($("tab-journal")?.classList.contains("active"))mount();});
setInterval(()=>{if($("tab-journal")?.classList.contains("active"))refresh();},30000);
})();