(()=>{'use strict';
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
let selectedId='es-reaction-v28',statusFilter='ALL',instrumentFilter='ALL';
function registry(){return window.FM_MODEL_REGISTRY||[]}
function runtimeFor(m){if(!m.runtimeService)return{status:'NOT DEPLOYED',message:'No production service'};const h=(window.FM_ORDERFLOW_STATE?.health||[]).find(x=>x.service===m.runtimeService)||{};return{status:String(h.status||'WAITING').toUpperCase(),message:h.message||'Service has not reported yet',updated_at:h.updated_at};}
function tone(status){const s=String(status||'').toUpperCase();if(s==='READY'||s==='LIVE')return'ready';if(s==='PENDING'||s==='WAITING'||s==='STARTING'||s==='DEGRADED')return'pending';return'not-ready';}
function filterButton(label,value,type,current){return`<button class="engine-filter ${current===value?'active':''}" data-filter-type="${type}" data-filter-value="${value}">${label}</button>`}
function executionPanel(m){if(m.id==='es-reaction-v28')return'';const x=m.execution||{},ready=m.readiness==='READY'&&x.status==='READY';return`<article class="panel execution-panel"><div class="execution-head"><div><div class="eyebrow">TRADE PLAN OUTPUT</div><h3>Entry · Structural Stop · Take Profit</h3></div><span class="readiness ${ready?'ready':'pending'}">${ready?'ACTIVE LEVELS':'PENDING'}</span></div><div class="execution-grid"><div><span>Entry</span><strong>${esc(ready&&x.entry!=null?x.entry:'—')}</strong></div><div><span>Structural Stop</span><strong>${esc(ready&&x.structuralStop!=null?x.structuralStop:'—')}</strong></div><div><span>Take Profit</span><strong>${esc(ready&&Array.isArray(x.takeProfits)&&x.takeProfits.length?x.takeProfits.join(' · '):'—')}</strong></div></div><p class="muted">${esc(x.note||'Execution levels publish only when this engine is READY and a valid setup is active.')}</p></article>`;}
function detail(m){const r=runtimeFor(m);return`<article class="engine-hero"><div><div class="engine-title-line"><span class="model-instrument">${esc(m.instrument)}</span><span class="readiness ${tone(m.readiness)}">${esc(m.readinessLabel)}</span></div><h2>${esc(m.name)}</h2><p>${esc(m.role)}</p></div><div class="engine-runtime"><span>Runtime</span><strong class="${tone(r.status)}">${esc(r.status)}</strong><small>${esc(r.message)}</small></div></article><div class="engine-detail-grid"><article class="panel"><div class="eyebrow">CURRENT USE</div><h3>Production Role</h3><p>${esc(m.productionUse)}</p></article><article class="panel"><div class="eyebrow">NEXT GATE</div><h3>What must happen next</h3><p>${esc(m.currentGate)}</p></article></div><article class="panel"><div class="eyebrow">VALIDATION STATE</div><h3>Research Evidence</h3><p>${esc(m.validation)}</p></article>${executionPanel(m)}<article class="panel"><div class="eyebrow">MODEL / SETUP SPECIFICATION</div><div class="engine-spec">${(m.spec||[]).map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div></article><article class="panel"><div class="eyebrow">FROZEN PARAMETERS / POLICY</div><p class="mono-copy">${esc(m.params)}</p><div class="tag-row">${(m.tags||[]).map(x=>`<span class="engine-tag">${esc(x)}</span>`).join('')}</div></article>`;}
function renderStrategy(){const panel=$('tab-model');if(!panel)return;const models=registry(),visible=models.filter(m=>(statusFilter==='ALL'||m.readiness===statusFilter)&&(instrumentFilter==='ALL'||m.instrument===instrumentFilter||m.instrument==='ES/NQ'));if(!visible.some(x=>x.id===selectedId))selectedId=visible[0]?.id||models[0]?.id;const selected=models.find(x=>x.id===selectedId)||visible[0];panel.innerHTML=`<div class="engine-page"><div class="section-head engine-head"><div><div class="eyebrow">MODEL GOVERNANCE + STRATEGY DEFINITIONS</div><h2>Strategy Engines</h2><p class="muted">Research readiness and runtime availability are separate.</p></div><div class="engine-count">${visible.length} / ${models.length} models</div></div><div class="engine-toolbar"><div class="engine-filter-group"><span>Status</span>${filterButton('All','ALL','status',statusFilter)}${filterButton('Ready','READY','status',statusFilter)}${filterButton('Pending','PENDING','status',statusFilter)}${filterButton('Not Ready','NOT_READY','status',statusFilter)}</div><div class="engine-filter-group"><span>Instrument</span>${filterButton('All','ALL','instrument',instrumentFilter)}${filterButton('ES','ES','instrument',instrumentFilter)}${filterButton('NQ','NQ','instrument',instrumentFilter)}</div></div><div class="engine-layout"><aside class="engine-list">${visible.map(m=>{const r=runtimeFor(m);return`<button class="engine-row ${m.id===selectedId?'selected':''}" data-engine-id="${esc(m.id)}"><div><span class="model-instrument">${esc(m.instrument)}</span><strong>${esc(m.shortName)}</strong><small>${esc(m.family)}</small></div><div class="engine-row-state"><span class="readiness ${tone(m.readiness)}">${esc(m.readinessLabel)}</span><small>${esc(r.status)}</small></div></button>`}).join('')||'<p class="muted">No models match this filter.</p>'}</aside><section id="engineDetail" class="engine-detail">${selected?detail(selected):'<div class="panel">No model selected.</div>'}</section></div></div>`;}
function bind(){document.addEventListener('click',ev=>{const row=ev.target.closest('[data-engine-id]');if(row){selectedId=row.dataset.engineId;renderStrategy();return}const f=ev.target.closest('[data-filter-type]');if(f){if(f.dataset.filterType==='status')statusFilter=f.dataset.filterValue;else instrumentFilter=f.dataset.filterValue;renderStrategy();}});}
function init(){const old=$('modelFleetOverview');if(old)old.remove();renderStrategy();bind();setInterval(()=>{if(document.querySelector('#tab-model.active'))renderStrategy();},5000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();