import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {ZOOM_STEPS,chartWindow,defaultGammaViewport,optionsFreshness,renderCompactGamma,renderOptionsAnalysis} from "../screener/options-analysis-view.js";
import {createUIState} from "../screener/ui-state.js";

const row={symbol:"SPX",spot:100,source_as_of:"2026-09-23T19:00:00Z",status:"CURRENT",payload:{spot:100,summary:{gamma_regime:"SHORT GAMMA",net_gex:-100,call_gex:100,put_gex:-200,gross_gex:300,call_wall:101,put_wall:99,zero_gamma:100.5,zero_gamma_status:"CURRENT",gamma_magnet:99},coverage:{contract_count:4,distinct_strike_count:2},strike_profile:[{strike:99,net_gex:-200},{strike:101,net_gex:100}],signals:[{type:"VOLATILITY",strength:"STRONG",description:"Proxy"}],analysis:{setup_state:"VOLATILITY EXPANSION RISK",setup_analysis:["<img src=x>"],trading_implication:"Context only"}}};
const widePayload={spot:100,strike_profile:Array.from({length:101},(_,i)=>({strike:50+i,net_gex:i-50}))};

test("gamma freshness remains fail closed",()=>{assert.equal(optionsFreshness(row,Date.parse("2026-09-23T19:01:00Z")),"CURRENT");assert.equal(optionsFreshness(row,Date.parse("2026-09-23T19:04:00Z")),"AGED");assert.equal(optionsFreshness(row,Date.parse("2026-09-23T19:06:00Z")),"STALE");});
test("all four tabs and safe analysis render",()=>{const h=renderOptionsAnalysis([row],"SPX",Date.parse("2026-09-23T19:01:00Z"),"READY",createUIState());for(const symbol of ["SPX","SPY","QQQ","IWM"])assert.match(h,new RegExp(`data-symbol="${symbol}"`));assert.match(h,/&lt;img src=x&gt;/);assert.doesNotMatch(h,/<img src=x>/);});
test("original V2.1 gamma zoom constants and controls are restored",()=>{assert.deepEqual(ZOOM_STEPS,{TIGHT:10,NEAR:20,WIDE:40});const h=renderOptionsAnalysis([row],"SPX",Date.now(),"READY",createUIState());for(const mode of ["TIGHT","NEAR","WIDE","ALL"])assert.match(h,new RegExp(`data-zoom="${mode}"`));});
test("options gamma defaults to NEAR",()=>{const h=renderOptionsAnalysis([row],"SPX",Date.now(),"READY",createUIState());assert.match(h,/data-zoom="NEAR" aria-pressed="true" class="active"/);});
test("home compact gamma is fixed TIGHT and has no controls",()=>{const h=renderCompactGamma(row,{},createUIState(),"SPX");assert.equal(chartWindow(row.payload,"TIGHT").zoom,"TIGHT");assert.doesNotMatch(h,/data-action="gamma-zoom"|gamma-zoom/);});
test("gamma chart has no wheel pinch pan or reset",()=>{const h=renderOptionsAnalysis([row],"SPX",Date.now(),"READY",createUIState()),source=readFileSync(new URL("../screener/options-analysis-view.js",import.meta.url),"utf8");for(const token of ["data-interactive-chart","chart-reset",">Reset<","Wheel/pinch","viewportFor","pinch","drag to pan"])assert.ok(!h.includes(token)&&!source.includes(token),token);});
test("selected gamma zoom survives repeated live-data renders",()=>{const ui=createUIState();ui.optionsZoom="WIDE";const first=renderOptionsAnalysis([row],"SPX",Date.now(),"READY",ui),second=renderOptionsAnalysis([{...row,source_as_of:"2026-09-23T19:01:00Z"}],"SPX",Date.now(),"READY",ui);for(const h of [first,second])assert.match(h,/data-zoom="WIDE" aria-pressed="true" class="active"/);});
test("chartWindow remains spot centered and ALL preserves complete profile",()=>{for(const mode of ["TIGHT","NEAR","WIDE","ALL"]){const view=chartWindow(widePayload,mode);assert.equal((view.low+view.high)/2,100);}assert.equal(chartWindow(widePayload,"ALL").rows.length,101);const d=defaultGammaViewport(widePayload);assert.equal((d.xMin+d.xMax)/2,100);});
test("point tooltips and signed gamma palette remain",()=>{const h=renderOptionsAnalysis([row],"SPX",Date.now(),"READY",createUIState()),css=readFileSync(new URL("../screener/styles.css",import.meta.url),"utf8");assert.match(h,/data-chart-point/);assert.match(h,/below spot|above spot/);assert.match(css,/\.chart-tooltip/);assert.match(css,/#26c983/);assert.match(css,/#f24567/);});
test("missing selected symbol fails closed",()=>assert.match(renderOptionsAnalysis([row],"SPY",Date.now(),"READY",createUIState()),/No current SPY analysis/));
test("legacy OI proxy language is replaced",()=>{const legacy=structuredClone(row);legacy.payload.signals[0].description="OI proxy is net negative";const h=renderOptionsAnalysis([legacy],"SPX",Date.now(),"READY",createUIState());assert.doesNotMatch(h,/OI proxy/i);assert.match(h,/gamma exposure/i);});
