import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {renderOptionChain} from "../screener/option-chain-view.js";
import {capturePageState,createUIState,restorePageState} from "../screener/ui-state.js";

test("UI store preserves all control families",()=>{const ui=createUIState({page:"home",demo:false});for(const key of ["optionsSymbol","optionsZoom","efficiencyTimeframes","efficiencyModes","efficiencyRecentOffsets","chainFilters","aiExpanded","aiDetailOpen","scrollPositions"])assert.ok(key in ui);assert.ok(!("chartViewports" in ui));assert.ok(!("chartTooltips" in ui));});
test("combined-chart selections persist independently through a simulated refresh",()=>{const ui=createUIState();ui.efficiencyTimeframes.SPX="M5";ui.efficiencyTimeframes.QQQ="M1";ui.efficiencyModes.SPX="FULL";ui.efficiencyRecentOffsets.QQQ=12;Object.assign({},ui);assert.equal(ui.efficiencyTimeframes.SPX,"M5");assert.equal(ui.efficiencyTimeframes.QQQ,"M1");assert.equal(ui.efficiencyModes.SPX,"FULL");assert.equal(ui.efficiencyRecentOffsets.QQQ,12);});
test("AI expansion persists per symbol",()=>{const ui=createUIState();ui.aiExpanded.SPY=true;ui.aiExpanded.QQQ=false;assert.equal(ui.aiExpanded.SPY,true);assert.equal(ui.aiExpanded.QQQ,false);});
test("AI detailed reasoning remains open across a live refresh",()=>{const ui=createUIState(),detail={dataset:{aiDetailKey:"current:SPX:slot:hash"},open:true};const root={querySelector(){return null;},querySelectorAll(selector){return selector==="details[data-ai-detail-key]"?[detail]:[];}};capturePageState(root,ui);assert.equal(ui.aiDetailOpen[detail.dataset.aiDetailKey],true);detail.open=false;restorePageState(root,ui);assert.equal(detail.open,true);});
test("option-chain filter and sort state survives live-data rendering",()=>{const ui=createUIState();Object.assign(ui.chainFilters,{security:"SPY",right:"CALL",askMin:"1",askMax:"5",sort:"gamma",direction:"desc"});const model={optionChain:[],chainPointers:[]};const first=renderOptionChain(model,ui),second=renderOptionChain({...model,optionChain:[]},ui);for(const html of [first,second]){assert.match(html,/data-value="SPY" aria-pressed="true"/);assert.match(html,/data-value="CALL" aria-pressed="true"/);assert.match(html,/value="1"/);assert.match(html,/value="5"/);assert.match(html,/<option value="gamma" selected>/);assert.match(html,/Descending/);}});
test("active app has no obsolete viewport state or interaction import",async()=>{const source=(await Promise.all(["../screener/cash-open-app.js","../screener/lppc-view.js","../screener/ui-state.js"].map(file=>readFile(new URL(file,import.meta.url),"utf8")))).join("\n");for(const token of ["chartViewports","chartTooltips","chart-interaction","resetViewport","bindChartInteractions"])assert.ok(!source.includes(token),token);});
